### ISSUE TITLE
Japanese 2k Sample Games are crashing on the newer Player.exe

### ISSUE THREAD

**Issue by jetrotal** [EasyRPG/Player#3013] opened 2023-05-21 01:52 UTC
Please fill in the following fields before submitting an issue:
#### Name of the game:
2k Sample Games - Abyss, Hanayome, Queen

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
 https://cdn.tkool.jp/updata/RPG2000_J.exe 

#### Describe the issue in detail and how to reproduce it:
I downloaded and unziped correctly (without Mojibake) the games Abyss, Hanayome, Queen

When I run them, all the games crash after selecting "new game" and create a big .dmp file.

Issue doesn't happen with 0.7 exe...

I wonder if is it something related with my settings file, since all the games are starting with widescreen window size, even though they are all marked as default resolution.

![image](https://github.com/EasyRPG/Player/assets/45118493/fa464337-5e3e-4a72-8e1d-3e2155fe57ba) 
![image](https://github.com/EasyRPG/Player/assets/45118493/07cb2e33-a746-429e-8c92-a454aee541dd)

---------------
edit: I randomly got it working after opening the easyrpg_log file and clearing all the content from it, can't tell why

easyrpg_log content
```
[2023-05-20 22:55:45] Debug: EasyRPG Player 0.8 (2023-04-29) started
[2023-05-20 22:55:45] Debug: =======================================
[2023-05-20 22:55:45] Debug: CLI: 
[2023-05-20 22:55:45] Debug: Clock: StdSteady steady=true period=ns (1 / 1000000000)
[2023-05-20 22:55:45] Debug: Seeded the RNG with 1684634145.
[2023-05-20 22:55:45] Debug: SDL2: RendererInfo hw=true sw=false vsync=true
[2023-05-20 22:55:45] Debug: SDL2: Detected format (0) SDL_PIXELFORMAT_ARGB8888 : rank=(2)
[2023-05-20 22:55:45] Debug: SDL2: Selected Pixel Format SDL_PIXELFORMAT_ARGB8888
[2023-05-20 22:55:45] Debug: Controller 0 (Xbox 360 Controller) added
[2023-05-20 22:55:45] Debug: Detected encoding: ibm-943_P15A-2003. Files not found (1/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: ibm-5346_P100-1998. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: UTF-16BE. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: UTF-16LE. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: ibm-5348_P100-1997. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: ibm-5349_P100-1998. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: windows-936-2000. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: Big5. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: ibm-5347_P100-1998. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: ibm-5347_P100-1998. Files not found (0/2). Trying next. [2x]
[2023-05-20 22:55:46] Debug: Bad encoding: KOI8-R. Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: windows-1254. Files not found (0/2). Trying next.
[2023-05-20 22:55:46] Debug: Detected encoding: ibm-943_P15A-2003
[2023-05-20 22:55:46] Debug: Game and Save Directory:
[2023-05-20 22:55:46] Debug: 1: [Native] 
[2023-05-20 22:55:46] Debug: Loading game 花嫁の冠
[2023-05-20 22:55:46] Debug: Analyzing RPG_RT RPG_RT.exe
[2023-05-20 22:55:46] Debug: EXEReader: EXFONT resource found (DE 0xacdd0; 0xb01c4; len 0x2168)
[2023-05-20 22:55:46] Debug: ExFont loaded from RPG_RT
[2023-05-20 22:55:46] Debug: EXEReader: VERSIONINFO not found
[2023-05-20 22:55:46] Debug: RPG_RT information: version= logos=1 i386=true easyrpg=false
[2023-05-20 22:55:46] Debug: Engine configured as: 2k=true 2k3=false MajorUpdated=true Eng=false
[2023-05-20 22:55:46] Debug: Adding C:\Program Files (x86)\Steam\steamapps\common\RPG Maker 2003\RTP to RTP path
[2023-05-20 22:55:46] Debug: RTP is "Don Miguel English Translation" (500/500)
[2023-05-20 22:55:46] Debug: Patch configuration: dynrpg=false maniac=false key-patch=false common-this=false pic-unlock=false 2k3-commands=false
[2023-05-20 22:55:46] Debug: Cannot find: Font/Font
[2023-05-20 22:55:46] Debug: Cannot find: Font/Font2
[2023-05-20 22:55:47] Debug: Resolution changed to 320x240
[2023-05-20 22:55:48] Debug: Starting new game
[2023-05-20 22:55:48] Debug: Game uses RTP "Official Japanese"
[2023-05-20 22:55:48] Debug: Loaded Map Map0014.lmu
[2023-05-20 22:55:48] Debug: Tree: オープニング < 花嫁の冠
[2023-05-20 22:55:49] Debug: Fluidsynth: Could not load soundfont.
[2023-05-20 22:55:49] Debug: WildMidi: Could not find configuration file.
[2023-05-20 22:56:06] Debug: EasyRPG Player 0.8 (2023-04-29) started
[2023-05-20 22:56:06] Debug: =======================================
[2023-05-20 22:56:06] Debug: CLI: 
[2023-05-20 22:56:06] Debug: Clock: StdSteady steady=true period=ns (1 / 1000000000)
[2023-05-20 22:56:06] Debug: Seeded the RNG with 1684634165.
[2023-05-20 22:56:06] Debug: SDL2: RendererInfo hw=true sw=false vsync=true
[2023-05-20 22:56:06] Debug: SDL2: Detected format (0) SDL_PIXELFORMAT_ARGB8888 : rank=(2)
[2023-05-20 22:56:06] Debug: SDL2: Selected Pixel Format SDL_PIXELFORMAT_ARGB8888
[2023-05-20 22:56:06] Debug: Controller 0 (Xbox 360 Controller) added
[2023-05-20 22:56:06] Debug: Detected encoding: ibm-943_P15A-2003. Files not found (1/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: ibm-5346_P100-1998. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: UTF-16BE. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: UTF-16LE. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: ibm-5348_P100-1997. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: ibm-5349_P100-1998. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: windows-936-2000. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: Big5. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: ibm-5347_P100-1998. Files not found (0/2). Trying next.
[2023-05-20 22:56:06] Debug: Detected encoding: ibm-5347_P100-1998. Files not found (0/2). Trying next. [2x]

```

**Comment by Mimigris** [comment] 2023-05-21 09:50
> Issue doesn't happen with 0.7 exe...

I've tried for Abyss, and this issue seems to be also present in version 0.7.0, so this is not a near regression at least.
For said game, the crash seems to appear when the Map0001.lmu has to be loaded.

When trying to start a new game with an old debug build from version 0.7.0 stored on my computer, this issue occurs (not that it may not exactly be that the cause of the issue now since it's an old version):
![image](https://github.com/EasyRPG/Player/assets/108797333/ab68ca5d-d0f9-4f6e-aaab-da35bf95cfcf)


> I wonder if is it something related with my settings file, since all the games are starting with widescreen window size, even though they are all marked as default resolution.

Since this issue also appears with version 0.7.0 and that I was able to replicate even with the default resolution in version 0.8.0, I guess that this is just unrelated. You probably changed the global configuration of your Player to be Widescreen and forgot to revert it.

**Comment by Ghabry** [comment] 2023-05-22 18:37
is not crashing on Linux here. Will need a test on Windows later.

@jetrotal can you upload one of the dmp files somewhere? Yes they are big but they indicate the crash location. Maybe gives a hint what went wrong for you.

**Comment by jetrotal** [comment] 2023-05-22 18:50
[Player_2023-05-20-23-23-57.zip](https://github.com/EasyRPG/Player/files/11535913/Player_2023-05-20-23-23-57.zip)

**Comment by Ghabry** [comment] 2023-05-22 19:07
Based on the dmp this is a duplicate of #2756

**Closed** 2023-06-04 16:44 UTC
Labels: Crash, Win32
