### ISSUE TITLE
Sound volume

### ISSUE THREAD

**Issue by Soeufans** [EasyRPG/Player#2236] opened 2020-05-30 20:55 UTC
#### Describe the issue in detail and how to reproduce it:

Hello!

I was recently creating my menu for the game, and i notice, that the "Volume" for the sounds, works different from RM2k3

I creat an event with fading a sound to volume 100 to 0 and with RPG maker 2003 the sounds get offf gradually  like this:

Volume:
100 --- > 100
90   ---> 90
80   ---> 80
70   ---> 70
60   ---> 60
50   ---> 50
40   ---> 40
30   ---> 30
20   ---> 20
10   ---> 10
0     --->   1
In the volume lower than 60, theres a "noise" on them

With Player Easy RPG, the sounds get off, but it looks like it goes like this (or is my ear)
Editor   ---> EasyRPG
100      --->    100
90        --->      95
80        --->      85
70        --->      75
60        --->      65
50        --->       55
40        --->       45
30        --->       35
20        --->       25
10        --->       15
0          --->         0

not exactly as these numbers i expose, maybe its my ears, but theres some difference betwen them

Heres a Video about the sound
[Easy Video sounds.zip](https://github.com/EasyRPG/Player/files/4706444/Easy.Video.sounds.zip)

**Comment by elsemieni** [comment] 2020-05-30 22:21
I used to think there's a similar issue that I talked about different volume scales, but I couldn't find it. 
I will document it again.

Seems RPG_RT volume scale is more sort-of-exponential one, meanwhile in Player volume scale is linear.
There's a visual example of the attached video example for seeing more clearly.
![image](https://user-images.githubusercontent.com/1494687/83339937-a4b4c980-a2a0-11ea-8e88-35599efc1ccd.png)

As workaround hotfix for SuperCrystalHunter's Player repo I implemented some sort of lookup table for correcting volume values closer to RPG_RT ones in https://github.com/elsemieni/easyrpg-player-ne-sch/blob/master/src/game_system.h#L79 and https://github.com/elsemieni/easyrpg-player-ne-sch/blob/master/src/game_system.cpp#L194 . However, didn't PR this one beacuse the hotfix is ugly code-speaking.

**Comment by rueter37** [comment] 2020-10-09 17:39
The diagram looks like a cubic (power of 3) curve to me, so we could try
`volume = (int)std::ceil(100.0 * std::pow(volume / 100.0, 3.0));`

**Comment by elsemieni** [comment] 2020-12-06 17:49
> ~The diagram looks like a cubic (power of 3) curve to me, so we could try `volume = (int)std::ceil(100.0 * std::pow(volume / 100.0, 3.0));`~
> Disregard my comment, the formula I had provided here doesn't exactly match @elsemieni's [lookup table](https://github.com/elsemieni/easyrpg-player-ne-sch/blob/master/src/game_system.h#L79).

Don't rely on my lookup table. That's just a vague approximation :)

**Comment by rueter37** [comment] 2021-03-20 11:21
Made volume tests with a VU meter and came to the following volume values (about 90% accuracy, for 100% accuracy we need to dig into the binary):
|Volume setting|Actual volume|
|---|---|
|100%|100%|
|90%|70%|
|80%|47%|
|70%|29%|
|60%|20%|
|50%|15%|
|40%|10%|
|30%|7%|
|20%|4%|
|10%|3%|
|1%|2%|
|0%|0%|

I have only tested in 10%-increments because RPG Maker allows setting the volume in 10%-increments only (but you can still get to intermediate settings by hex editing the files). And there seems to be a volume floor if the volume is greater than 0%. Moreover judging by the steps in the volume table there does not seem a mathematical formula being used to get the actual volume values. Using the volumes in the table provided here makes the rain in "Vampires Dawn" sound right (tested it myself). I recall the rain was mentioned in #2427.

**Comment by carstene1ns** [comment] 2021-03-20 13:21
Maybe not too useful:
![Figure_1](https://user-images.githubusercontent.com/4691314/111870901-921e9480-8987-11eb-98be-dcf54253b4ce.png)

**Comment by rueter37** [comment] 2021-03-20 13:26
@carstene1ns Thank you for providing the chart! I think the formula used in the green curve is a good approximation to avoid having to use a volume lookup table.

**Comment by Ghabry** [comment] 2021-03-20 14:06
I think this is caused by DirectSound. Harmony calls into a Dsound.dll function.
Harmony is just doing 100 - (fade-volume) / 100 and passes this to a dsound func.

**Comment by Ghabry** [comment] 2021-03-20 14:27
I found e.g. this in old Dolphin emu code (before they dropped dsound):

https://github.com/dolphin-emu/dolphin/blob/4.0/Source/Core/AudioCommon/Src/DSoundStream.cpp#L132

**Comment by Ghabry** [comment] 2021-03-20 18:22
Via IRC
@rueter37 
Got the sound volume formula now! Pseudo-code: volume = (10 ^ ((-100 + volume)/60.0)) * 100

I will assign this to me as this is audio code.

**Comment by Ghabry** [comment] 2021-04-08 21:26
Something else of interest @elsemieni @rueter37 
There is also an option for controlling the "Panning" (whether the sound is left or right). Guess this is also implemented by adjusting the volume but per channel, not in general. Could you check how the loudness per channel changes depending on the panning?

Will do this stuff after Midi. Need to get some order in here :)

**Comment by rueter37** [comment] 2021-04-09 12:36
The panning scales linear but the sound volume formula gets applied afterwards. Here is a table for 100% volume sounds:

| Panning | Volume left | Volume right | Actual volume left | Actual volume right |
|-|-|-|-|-|
| 0 (full left) | 100% | 0% | 100% | 0% |
| 10 | 100% | 20% | 100% | 4% |
| 20 | 100% | 40% | 100% | 10% |
| 30 | 100% | 60% | 100% | 21% |
| 40 | 100% | 80% | 100% | 46% |
| 50 (default, center) | 100% | 100% | 100% | 100% |
| 60 | 80% | 100% | 46% | 100% |
| 70 | 60% | 100% | 21% | 100% |
| 80 | 40% | 100% | 10% | 100% |
| 90 | 20% | 100% | 4% | 100% |
| 100 (full right) | 0% | 100% | 0% | 100% |

**Comment by Ghabry** [comment] 2021-05-31 19:43
@rueter37 I'm pretty sure I saw a patch by you somewhere. Cannot find it anymore.

Anyway. I'm pretty sure by now that all platforms we are targeting use a linear volume (or are converted like SDL2 when using DSound as a backend). So doing the translation in Game_System makes sense.

This would also give us extra flexibility: One could add an extra chunk to define that the volume scale for this track is linear instead of logarithmic.

**Comment by rueter37** [comment] 2021-05-31 19:49
@Ghabry here you go: https://github.com/rueter37/player/tree/volume-scaling-change

**Comment by Ghabry** [comment] 2021-05-31 19:52
great. Add a "// Adjust to RPG_RT (Direct Sound) volume scale" and you can PR it.

I will keep myself assigned here because the Panning is more tricky (must be supported in all backends).

**Comment by Ghabry** [comment] 2021-05-31 19:53
wait, this wasn't added for BGM, is this intentional? Guess BGM needs the same.

**Comment by rueter37** [comment] 2021-05-31 19:54
I'm not sure if BGM is affected as well.

**Comment by Ghabry** [comment] 2021-05-31 19:55
okay then this must be measured before a PR makes sense. Sorry :)

**Comment by rueter37** [comment] 2021-06-01 16:20
Did some tests and found out that BGM is affected as well. I have updated my patch now, I can PR it now if you want.

**Comment by Ghabry** [comment] 2021-06-01 16:25
Yes please do

**Comment by Ghabry** [comment] 2021-07-18 23:46
the actual issue is fixed here. I will create a new one for panning

**Closed by Ghabry** 2021-07-18 23:46 UTC
Labels: Audio
