### ISSUE TITLE
Player should not display warnings on missing audio RTP files

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1672] opened 2019-03-06 08:33 UTC
I suggested this as part of a review comment in #1630. It seemed to be fixed, but the issue persists and we got a couple of email reports because there are broken games. Game devs don't detect this quite often because RPG_RT does not complain and silently ignores them, so they should go to debug output to match the behavior.

**Comment by Ghabry** [comment] 2019-03-06 08:36
The part where we disabled the Warning is:
The game uses FullPackageFlag and RTP sounds are missing.

In the other cases this is now by design because we got bug reports that Sounds are not playing.

**Comment by Ghabry** [comment] 2019-03-06 08:45
There are also two reports in the Yume Nikki Discord because of Warnings in Yume2kki and they can't fix them because they don't have a Computer...
I think for 0.6.1 we have to reevaluate who is worse, the ones complaining about missing sounds or the ones about the RTP warning.

**Comment by carstene1ns** [comment] 2019-03-06 12:00
I guess we should just extend the check to exclude sounds in general.
The other bug report mail (Eternal Legends) is probably related to converted wave files (or, the warning is real and the RTP was not installed correctly https://youtu.be/cphNpqKpKc4)

**Comment by fdelapena** [comment] 2019-03-06 18:56
Just as a note, this covers sounds and music folders

**Comment by carstene1ns** [comment] 2019-03-07 18:30
> There are also two reports in the Yume Nikki Discord because of Warnings in Yume2kki

Would be interesting to know, which warning was triggered there.

Yume2kki is at least problematic, since there are many different authors and likely nobody knows who introduces such bugs (also the manipulated path issue we had before).

**Comment by Ghabry** [comment] 2019-03-07 19:52
no jp keyboard here written in romaji: The missing file is "Sound/gashan" (glass).

**Comment by fdelapena** [comment] 2019-04-18 02:11
A mixed, dirty provisional solution proposal: silence RTP audio warnings just for system database sounds (and from them, those changed later in-game) because they are used a lot and fill the console.

**Comment by Ghabry** [comment] 2019-04-18 10:20
Well now that we finally have good installers for 2k and 2k3 RTP we could create another app which downloads and installs the RTP on Android ;)

**Comment by fdelapena** [comment] 2019-04-23 21:41
Worked around at https://github.com/EasyRPG/Player/pull/1754/commits/45ce920a2e7aa1a14f21511455ed1616635132ed

**Comment by Ghabry** [comment] 2019-07-14 19:21
fixed by #1754

**Closed by Ghabry** 2019-07-14 19:21 UTC
Labels: Audio, FileFinder, Patch available, UX
