### ISSUE TITLE
Destined: Boss picture moves upwards when damaged

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1741] opened 2019-04-07 19:22 UTC
#### Name of the game:
Destined https://rmarchiv.tk/games/1922

#### Attach files (as a .zip archive or link them)

The official save that doesn't load in RPG_RT:
[Save12.zip](https://github.com/EasyRPG/Player/files/3051959/Save12.zip)

Custom save by me obtained via "--start-map-id 193 TestPlay Window --start-party 2" that loads in RPG_RT:
[Save14.zip](https://github.com/EasyRPG/Player/files/3051967/Save14.zip)
(Hero doesn't receive damage because it is Don and not Alex, not a bug)

Load the save with RPG_RT (note: For some reason RPG_RT is RPG_RT2.exe because the normal one is EasyRPG :/).

#### Describe the issue in detail and how to reproduce it:

Walk upwards, after the cutscene attack the small slimes by mashing DECISION, then the big slime shrinks and moves upwards.

Because the event code is only move picture (always at the same coordinate!) I assume this is a X/Y miscalculation of Move picture when combined with zoom changes.

**Comment by fmatthew5876** [comment] 2019-04-11 03:13
Whats the bug here? When I play this with RPG_RT and attack slimes, the big slime also moves up.

**Comment by Ghabry** [comment] 2019-04-11 08:05
did you see my note? "Load the save with RPG_RT (note: For some reason RPG_RT is RPG_RT2.exe because the normal one is EasyRPG :/)."

**Comment by fmatthew5876** [comment] 2019-04-11 23:55
I must have gotten this from a different place than you, because mine doesn't have `RPG_RT2.exe`

Anyone have a proper download link for this game? It's name is hard to google.

**Comment by Ghabry** [comment] 2019-04-12 05:44
Oh didnt notice that the DL link is missing. added

**Comment by fmatthew5876** [comment] 2019-04-13 00:48
Ok so for this one, the `RPG_RT2.exe` works as expected. The big slime stays put and just gets smaller. If I upgrade `RPG_RT.exe` to rm2ke, the bug we see in player happens.

So I guess there is something about these move picture commands where the position doesn't change in old versions of `RPG_RT.exe`

```
0000: code=MovePicture(11120) indent=0 str="" params=[1 0 160 -15 0 185 0 0 80 80 120 100 0 15325932 10 1]
0000: code=MovePicture(11120) indent=0 str="" params=[1 0 160 -15 0 160 0 0 80 80 120 100 0 5497976 10 1]
```

**Comment by fmatthew5876** [comment] 2019-04-13 03:01
Confirmed with `--engine rpg2k` the bug still exists. So there is some difference in move picture behavior with `fixed_to_map` in Don's rm2k vs newer rm2k versions.

So in order to fix this, we need to:
- [ ] Implement whatever the show picture / move picture behavior is here and which rm2k versions it applies to
- [ ] Correctly detect the engine version for this game and possibly others.

**Comment by carstene1ns** [comment] 2019-04-13 12:23
May also be worth to check #1126 (testcase, possible regressions).

**Comment by Ghabry** [comment] 2019-05-23 09:28
@fmatthew5876 
Can you provide a test case for this? Somehow I'm unable to create picture commands that exhibit this behaviour. (I use the RPG_RT from Vampires Dawn, which should be Dons version).

**Comment by Ghabry** [comment] 2019-05-23 09:31
are you sure this is Don Miguels RPG_RT? Don is a very old RPG_RT version that depends on harmony.dll, but this engine version doesn't use Harmony.

**Comment by fmatthew5876** [comment] 2019-05-26 18:28
> are you sure this is Don Miguels RPG_RT? Don is a very old RPG_RT version that depends on harmony.dll, but this engine version doesn't use Harmony.


From `Destined -  [Vollversion-1.0]-2005-06-14.zip`:

```
$ md5sum Destined/*.exe                                    
6948fc9d8cb13d46b69e8d442d18009d  Destined/RPG_RT2.exe                               
e476c9621b60f8c39cd1ab2de2a58d97  Destined/RPG_RT.exe
```

From my installed copy of Don's rm2k:

```
.../RPG2000/Project/SAMPLE GAME$ md5sum RPG_RT.EXE
6948fc9d8cb13d46b69e8d442d18009d  RPG_RT.EXE
```

**Comment by fmatthew5876** [comment] 2019-12-03 04:25
So this is a difference between older versions of rm2k. To test simply put a picture on the screen with "Scroll to map" checked.

Then walk somewhere and talk to an event which moves the picture.

In Don's rm2k, the picture will not move. In Value or Steam, the picture will move to that position and then stay there fixed to the map.

Destined was using `MovePicture` to animate the slime boss and taking advantage of the old behavior of not moving the picture.

**Comment by fmatthew5876** [comment] 2019-12-03 04:43
#1969 adds support for the correct MovePicture behavior in Don's rm2k.

Unfortunately we can't close this issue when that PR is merged because Player still incorrectly detects Destined as Steam rm2k and so the bug will still happen. If you played Destined with `--engine rpg2k` and #1969, the behavior will be correct.

**Comment by Ghabry** [comment] 2019-12-23 09:46
@fmatthew5876 
The game is incorrectly detected because the one uploading to rmarchiv.tk replaced RPG_RT.exe with EasyRPG Player. The proper file is RPG_RT2.exe, when you rename it back the result is:

```
Debug: Using RPG2k Interpreter
Debug: RPG2k < v1.50 / RPG2k3 < v1.05 detected
Debug: Engine configured as: 2k=1 2k3=0 MajorUpdated=0 Eng=0
```

which I consider correct.

**Comment by fmatthew5876** [comment] 2020-03-07 20:33
If that's the case I guess we can consider this fixed?

Unless we put some special one off hack for this one game that is packaged poorly, I'm not sure what else we can do here.

**Comment by carstene1ns** [comment] 2020-03-09 10:52
Yes, I think we can close this. The game should be packaged correctly on rmarchiv instead. Our detection is useless, when the executable is renamed. One would need to add engine info to `RPG_RT.ini` or something when shipped with different `RPG_RT.exe`. See #627.

**Closed by carstene1ns** 2020-03-09 10:52 UTC
Labels: Event/Interpreter, Needs feedback, Pictures
