### ISSUE TITLE
Android severe performance regression

### ISSUE THREAD

**Issue by Brianum** [EasyRPG/Player#1387] opened 2018-06-29 15:28 UTC
Severe performance regression on Android since commit 619f05b / Jenkins Build 675 - FPS drop in many situations.

#### Describe the issue in detail and how to reproduce it:
Fade to/animation in title screen is slow
Compare performance to Play Store build (Jenkins:672) / Jenkins Build 673 (last good build)
Start new game, skip intro. Observe low FPS on the first map. (around 10 FPS vs 60 FPS in older build)
Teleportation transitions are really slow as well.
"Ostmark" (larger village map, from the starting map just go west) also has low FPS
Battles/Battle Animations are also slow (from first map, go north)
Disabling audio does not improve FPS

**Comment by Ghabry** [comment] 2018-06-29 15:59
The problem is in the Android buildscript, the CFLAGS don't contain "-O2"..

You already have an open PR in buildscripts repo, could you add "-g0 -O2" to this line:
https://github.com/EasyRPG/buildscripts/blob/797d0c0aff42c19691031a13169d3f1fa00c3e95/android/2_build_toolchain.sh#L74

**Comment by Brianum** [comment] 2018-06-29 16:45
Yes, this does restore the performance to the previous level.

**Comment by Ghabry** [comment] 2018-07-02 07:43
This should be fixed now after recompiling the Android SDK

**Closed by Ghabry** 2018-07-02 07:43 UTC
Labels: Android, Building, Performance
