### ISSUE TITLE
Timer 1 in wrong position & the Event Touch is detected before

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#886] opened 2016-05-05 15:32 UTC
Hi there,
Look, **Timer 1** generally appears on the top-left screen corner. In this case, above the **Status Time** box.
About the **Event Touch**: it can be seen better when Alex touch the event from sides in EasyRPG Player.

RPG_RT
https://youtu.be/NqvziU82gSk

EasyRPG Player
https://youtu.be/56chY_mM-1A

By the way, in this mini-game test is more difficult to catch items in RPG_RT than EasyRPG

Testcase: [Collisions.zip](https://github.com/EasyRPG/Player/files/1220324/Collisions.zip)

---

Fixed:
- [x] timer1 position
- [ ] event touch

(Edited by @carstene1ns to make the status of this bug visible in the overview)

**Comment by Zegeri** [comment] 2016-05-10 17:23
The first issue is fixed here 3ffdd70b8ab. About the event touch issue, it might be hard to tell from the video. I've tried to isolate the issue in [this test project](https://dl.dropboxusercontent.com/u/30277047/TestTouch.7z) and I got the opposite impression. It looks like it would be more difficult to catch items in EasyRPG than in RPG_RT. Run that test project both with RPG_RT and Player: in RPG_RT, the hero collides with the moving event, while in Player doesn't.

**Comment by carstene1ns** [comment] 2017-08-13 07:15
Added the testcase from IRC link.

**Comment by Ghabry** [comment] 2018-09-04 22:47
The problem is that touch events only count when the move is finished:

![collision](https://user-images.githubusercontent.com/1331889/45061560-48aa1a80-b0a5-11e8-9bd1-0c9745dd4a67.gif)

**Comment by Ghabry** [comment] 2018-09-04 22:57
But one corner case: When the event is not moving the touch event triggers immediately (on the 1st frame of movement onto the tile)

**Comment by Ghabry** [comment] 2018-09-23 10:42
Moving the collision patch to 0.5.5/0.6 because this is a total mess:

New test case:

[Collisions+priorities.zip](https://github.com/EasyRPG/Player/files/2408629/Collisions%2Bpriorities.zip)

Going to prepare a table :/

**Comment by Ghabry** [comment] 2019-02-12 13:14
Because this is event collision related I will postbone this to 0.6.x and ping @fmatthew5876 as this is probably related to #1628

**Comment by Br4ssman** [comment] 2019-03-01 09:22
The events routes and collisions need to be fixed, but in SCH there is a new clue: the jewels, power-ups and power-down, are charsets with graphic from tilesets (16x16), Is it possible that EasyRPG use all event graphics like charsets graphics?

**Comment by Ghabry** [comment] 2019-03-02 11:15
@fmatthew5876 
More event touch vs player/collision touch:

This test case I linked few posts above: https://github.com/EasyRPG/Player/files/2408629/Collisions%2Bpriorities.zip

**Comment by fmatthew5876** [comment] 2019-03-17 13:55
I think this is fixed by #1697 but it's hard to tell.

Could use a second opinion

**Comment by Ghabry** [comment] 2019-03-22 16:08
When my tests in the zip are fixed the one in the game should be also fixed. Testing this later

The problem is basicly what I had shown in that gif: https://github.com/EasyRPG/Player/issues/886#issuecomment-418542261

**Comment by Ghabry** [comment] 2019-04-20 20:25
this is indeed fixed by 1697

**Closed** 2019-04-20 20:50 UTC
Labels: Event/Interpreter, Patch available, Testcase available
