### ISSUE TITLE
Sound problem vampire dawn 

### ISSUE THREAD

**Issue by kevin556** [EasyRPG/Player#453] opened 2015-04-22 14:28 UTC
There is a problem with playing a sound file Rain1.wav, when arriving at the dracula castle a message is displayed : Could not play Rain1 SE No Free channels available.

![capture d ecran 2015-04-22 a 16 26 12](https://cloud.githubusercontent.com/assets/3003278/7276772/7096649a-e90c-11e4-90c6-1e7f6e73cb46.png)

Oh and I'm on mac os maverick 10.9.5 on a macbook pro retina

**Comment by fdelapena** [comment] 2015-08-27 15:08
@kevin556 thanks for reporting, could you provide the map number or a savegame near this place to find this particular scene? The castle has a lot of maps.

**Comment by PK512** [comment] 2015-11-01 21:43
The problem ist still existing. This error is not related to a specified map, it's caused by the Common Event 0014:Regen. This event is active every time the hero is outside. It seems that there ist not enough wait time before the sound effect is called again and again. The orginal RPG_RT ignores it, if the sound effect is already playing. But in easyRPG the sound is overlayed.
I think the solution could be this easy: If the command "Play Sound Effect" executes a sound, that is already playing, it should be ignored.

I deactivated the Common events 14-17 to make Vampires Dawn playable for me.But this results in no weather.

**Comment by carstene1ns** [comment] 2015-11-01 22:15
Thanks for the details.
> I think the solution could be this easy: If the command "Play Sound Effect" executes a sound, that is already playing, it should be ignored.

This seems easy, but implementing it will actually cause a bit of work.
Currently, the sounds are played "fire and forget", this means `SDL_mixer` gets a sound file passed and plays it entirely on it's own on the next free channel.
We would need to maintain a list of which sound is played on which channel and sync it when changes occur (i.e. when a sound effect is over, the channel gets available again and the association needs to be cleared). Same goes for the `OpenAL` backend.
If this is going to be implemented in `game_system.cpp`, this would affect all audio backends. However, channel specific data is not easily available then.

**Comment by Ghabry** [comment] 2015-11-01 23:47
This is a high priority task because it's super annoying and not that hard to fix. Thanks for tracking it down.

Just some notes how to fix this (for the devs):
Yeah this needs additional logic in SDLAudio and AlAudio.
They must remember the channel -> filename mapping and then add new functions:

BGS_Finished(callback_function)

callback_function taking a const char* argument which is the filename

Game_System registers BGS_Finished (because the Audio functions have no dependencies on Game_* it must be done in this way) and tracks it this way...

**Comment by Ghabry** [comment] 2015-11-07 14:13
Actually RPG Maker also overlays similiar Sound effects, so this is unrelated with this issue

**Comment by Ghabry** [comment] 2015-11-07 16:03
Wasn't a sound issue at all but an interpreter bug (hooray!)

**Comment by Ghabry** [comment] 2015-11-07 16:10
Maybe all interpreter bugs should result in acoustic pain, makes them easier to detect :D

**Comment by carstene1ns** [comment] 2016-02-16 11:54
Got a mail report about this today, either this has regressed or the user has an old version...

**Comment by Ghabry** [comment] 2016-02-16 21:47
I'm quite certain this is Player#757

The bug is triggered when the interpreter is in a Loop and when the saving occurs while the interpreter is at "Repeat loop" it will leave the loop :(

**Comment by Ghabry** [comment] 2016-02-16 21:48
So this is actually a different bug triggering the same behaviour ;)

**Comment by Ghabry** [comment] 2016-02-16 22:26
Closing this bug again because the real issue was fixed and was only retriggered because of another bug.

**Closed by Ghabry** 2016-02-16 22:26 UTC
Labels: Interpreter, Savegames
