### ISSUE TITLE
Broken Animations (Battle)

### ISSUE THREAD

**Issue by PyredSalsa** [EasyRPG/Player#1496] opened 2018-11-11 02:00 UTC
**Game:** Alter A.I.L.A. Genesis

**Platform:** Windows/Android, ...
**Version:** v0.5.4 (Nov. 9) / Nightly Build (Nov. 10)

Attached a .gif of the issue, as well as the easyrpg_log.txt. The issue should be universal to every battle in the game, since all the battle animations were broken from the November 9th update onward. Also, I noticed that none of my attacks were showing the amount of damage dealt.

![brokenanimation](https://user-images.githubusercontent.com/44935031/48308147-7b501380-e52b-11e8-91a1-2ecf12dccf39.gif)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/2568986/easyrpg_log.txt)

**Comment by Ghabry** [comment] 2018-11-11 08:08
Hm, this sounds like a regression. Thanks, for the report.

**Comment by PyredSalsa** [comment] 2018-11-11 15:42
No problem. Just doing my civic duty, I suppose.

**Comment by Ghabry** [comment] 2019-02-26 21:31
No damage values displaying is not a regression but the broken battle animations are.

I'm not sure if this will be fixed because 0.6 is approaching and I'm currently ordering bugs by priority and this one has very low priority.

As for the 2000 battle system there will be a huge code refactor for the 2003 battle system coming later (for 0.6.1 then) which will hopefully nuke all such bugs forever.

**Comment by Ghabry** [comment] 2019-02-28 21:05
The no damage displaying is more complex than expected:
All attacks miss for some reason which makes sense because the base value is 0.
It could be caused by some incorrect event execution, one battle has 52 pages (!).

**Comment by Ghabry** [comment] 2019-02-28 22:00
The battle animations are broken due to 97fb076e0efb40a4843332a21c5a3492c699f781 but imo this commit is correct and the animations don't have the wait-flag set.

This needs more investigation, postboning.

**Comment by Ghabry** [comment] 2019-06-07 21:20
still no progress on this one, moving to 0.6.2 as this is 2k3 battle system

**Closed** 2021-03-22 01:05 UTC
Labels: Battle, Patch available, Regression
