### ISSUE TITLE
End roll crashing

### ISSUE THREAD

**Issue by freshiiness** [EasyRPG/Player#1769] opened 2019-05-16 22:10 UTC
End roll is constantly crashing after the 3rd dialouge in the burying one

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

**Comment by carstene1ns** [comment] 2019-05-16 22:14
Can you upload a savegame from before the crash?

**Comment by freshiiness** [comment] 2019-05-16 22:15
no i cant because i cant save in the middle of battle

**Comment by carstene1ns** [comment] 2019-05-16 22:18
Otherwise a logfile would be nice as well.

**Comment by freshiiness** [comment] 2019-05-16 22:20
alright

**Comment by Ghabry** [comment] 2019-05-17 08:27
The Burying one seems to be the name of a monster, maybe is possible to find it in the Database and run a test battle.
checking this later.

**Comment by Ghabry** [comment] 2019-05-23 09:15
Closing this as "Can't reproduce" (tested with 0.6). Fought through battle 14 without any issues.

Anoter minor problem: Because we don't differentiate between encoding and game language the battle contains japanese particles in the texts (game must be played with japanese encoding, due to the filenames, the game references japanese RTP).

**Closed by Ghabry** 2019-05-23 09:15 UTC
Labels: Crash, Invalid
