### ISSUE TITLE
Item use is abnormal

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1763] opened 2019-05-08 14:35 UTC
(this is a post 0.6 regression)

Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
Use item:飛行船遙控器
The flight ship did not appear. The character could not move.

**Comment by fdelapena** [comment] 2019-05-09 04:59
@s9060666 thank you for the bug report. There are multiple games with the same name (巴哈姆特), could you specify by providing a game download link?

**Comment by s9060666** [comment] 2019-05-09 10:30
> @ s9060666謝謝你的bug報告。有多個同名遊戲（巴哈姆特），您可以通過提供遊戲下載鏈接來指定嗎？
This is the URL of the game download.
http://www.mediafire.com/file/uqulbd1ggt9uuvw/

**Comment by s9060666** [comment] 2019-05-09 10:31
@fdelapena 
This is the URL of the game download.
http://www.mediafire.com/file/uqulbd1ggt9uuvw/

**Comment by Ghabry** [comment] 2019-05-25 22:17
To extract the lzh use ``unar -e cp950`` (Big5/Traditional chinese)

**Comment by Ghabry** [comment] 2019-05-25 22:28
Works for me in 0.6 and nightly. Closing as invalid for now.

@s9060666 
Do you have a savegame (LSD) for us where this can be reproduced?

**Comment by s9060666** [comment] 2019-06-03 09:10
@Ghabry 
https://drive.google.com/file/d/1-9BHTUwnmKY4JAcAtyN5D3i8GaOvnBRl/view?usp=drivesdk

**Comment by Ghabry** [comment] 2019-06-03 21:06
hm, with this save it is indeed reproducible. That is interesting. It works in 0.6 but not in our nightly build... let me test some PR builds

**Comment by Ghabry** [comment] 2019-06-03 21:13
I reupped the save: 
[Save03.zip](https://github.com/EasyRPG/Player/files/3249494/Save03.zip)

@fmatthew5876 this one is interesting. Use the item described 飛行船遙控器, is the last in the list. in 0.6 the airship appears. In master, #1771 and #1784 it is broken.

**Comment by fmatthew5876** [comment] 2019-06-04 01:40
This bug is move route (possibly collision) related

![chinesegame](https://user-images.githubusercontent.com/1198466/58845157-20594780-8648-11e9-83e9-89ae1def47b4.png)

When you use the item, this code is run. The event gets stuck at `WaitForAllMovement`

**Comment by fmatthew5876** [comment] 2019-06-04 02:03
So here's the bug with this one.

This must be an old EasyRPG save game, because the Vehicle events do not have their `vehicle` chunks set properly. When we save with RPG_RT, the `vehicle` chunk is normally always present for the boat, ship, and airship events.

Our new collision code uses the `vehicle` chunk to do vehicle specific checks. Since its missing from the save, the airship gets treated like a normal event and gets stuck on the water.

Interestingly, not only does RPG_RT work with this save, but if you load this save game and then save a new game, the `vehicle` chunks will still remain as 0.

So there are 2 possible fixes here:
1. Always overwrite the `vehicle` chunks when we load saved games. This is not strictly RPG_RT compatible, but without hacking there is no way to create an RPG_RT save game without these chunks anyway.
2. Refactor our collision code to work differently for the 3 `Game_Vehicle` events and ignore the chunk. More RPG_RT compatible, but requires big code changes just for something that can only happen due to broken saves to begin with..

I vote for (1) ..

**Comment by Ghabry** [comment] 2019-06-04 07:44
Ah this explains why I couldn't reproduce it without this savegame.

Method one is fine

**Closed** 2019-06-04 09:29 UTC
Labels: Event/Interpreter, Patch available, Regression, Savegames

**Comment by s9060666** [comment] 2019-06-04 13:13
@Ghabry Is there a way to fix it in the near future?

**Comment by fmatthew5876** [comment] 2019-06-04 13:20
@s9060666 

This is now fixed in master

**Comment by s9060666** [comment] 2019-06-04 14:13
@fmatthew5876 
When will it be put on the play store?

**Comment by fdelapena** [comment] 2019-06-04 14:25
@s9060666 it may take some weeks yet. In the meanwhile, you can try the following build:

https://ci.easyrpg.org/job/player-android/lastSuccessfulBuild/artifact/builds/android/app/build/outputs/apk/EasyRpgPlayerActivity.apk
