### ISSUE TITLE
Android: Support adding of additional buttons to the user interface

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#288] opened 2014-07-01 21:49 UTC
.

**Comment by fdelapena** [comment] 2015-03-22 22:23
@BlisterBoy if you use the text "fixes #437" or "closes #437" instead of "fix #437", the issue is closed automatically when merged.

**Closed** 2015-03-22 23:29 UTC
Labels: Android, UX

**Comment by BlisterBoy** [comment] 2015-03-22 23:32
Okay I'll remember, thanks for the tips !
