### ISSUE TITLE
Embric of Wulfhammer's Castle: Designer Room background changes incorrectly

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#961] opened 2016-07-27 20:13 UTC
In one specific room in this game there's a bug causing the room background to change suddenly upon movement to/from a certain area.

As usual, this video explains it better: https://www.heavylobster.com/files/another_bug.mp4

(also tested in RPG_RT, the background doesn't magically change there.)

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Savegame: https://www.heavylobster.com/files/Save05.lsd

How to reproduce this bug should be quite clear from the video.

**Comment by carstene1ns** [comment] 2016-07-27 20:15
This looks a bit like #761.

**Comment by Siltala** [comment] 2016-07-27 20:19
Oh, it does actually look very similar. Sorry, must have missed that one.

**Comment by carstene1ns** [comment] 2016-07-27 20:20
![map_props](https://picload.org/image/rrooldig/20160727221833_936x534.png)
Confirmed, closing as duplicate.

**Comment by carstene1ns** [comment] 2016-07-30 23:07
This could be a simple off-by-one error, because this seems to fix it:
```patch
diff --git a/src/game_map.cpp b/src/game_map.cpp
index aca22d8..800c282 100644
--- a/src/game_map.cpp
+++ b/src/game_map.cpp
@@ -386,7 +386,7 @@ void Game_Map::ScrollRight(int distance) {
                                parallax_x -= distance / 2;
                }
        } else {
-               if (map_info.position_x + distance <= (GetWidth() - 20) * SCREEN_TILE_WIDTH) {
+               if (map_info.position_x + distance < (GetWidth() - 20) * SCREEN_TILE_WIDTH) {
                        map_info.position_x += distance;
                        if (map_info.parallax_horz)
                                parallax_x -= distance / 2;
```

However, we still have jumping glitches, when the background is smaller than the map.

**Comment by carstene1ns** [comment] 2016-09-08 23:37
I am not sure, if I should add this shortly before release...
Do we know any other game with a parallax background, that does not have loping maps?

**Comment by Ghabry** [comment] 2016-09-08 23:41
There is a parallax background test in TestGame-2000 and I didn't observe this problem there.
Neither in Ara Fell.

**Comment by Ghabry** [comment] 2016-09-09 18:56
I created a 0.5.1 milestone for release in ~2 months. You can move this there if you want. Will do the same for my nobihaza 1 issue because I cant fix it completely :(

**Closed** 2016-10-04 09:20 UTC
Labels: Patch available, Window/Scenes
