### ISSUE TITLE
Wrong colors when changing screen tint

### ISSUE THREAD

**Issue by trotterdotp** [EasyRPG/Player#476] opened 2015-05-14 11:27 UTC
Changed screen tint to 60/60/70/70.
Using RTP tileset, a simple test project.

In RM :
http://i.imgur.com/ubMFIoM.png

In Easy RPG Player:
http://i.imgur.com/ZIwRTVC.png

Another example:
http://i.imgur.com/jWmXE1o.png

**Comment by BlisterBoy** [comment] 2015-05-14 11:38
Hi Trotter :), hope that other frenchies will come sooner ^^.

For those who didn't notice, in the second screen the rock near the middle of the screen becomed pink.

**Comment by Ghabry** [comment] 2015-05-14 14:23
Thx but the report, but screen Tone/Saturation bug is already know.
Closing as a duplicate of #357

**Closed by Ghabry** 2015-05-14 14:23 UTC
