### ISSUE TITLE
Yume2kki: Wallpaper selection looks different

### ISSUE THREAD

**Issue by purupurupuruin** [EasyRPG/Player#2519] opened 2021-05-04 01:41 UTC
#### Name of the game:
Yume2kki (Version 0.116)
(Download is at https://yume2kki.fandom.com/wiki/Downloads)

#### Player platform:
Linux

#### Attach files (as a .zip archive or link them)

Wallpaper selection in RPG_RT:
![Screenshot_2021-05-03_18-22-12](https://user-images.githubusercontent.com/64451846/116953064-25aeda80-ac41-11eb-816a-dc6a806f12b8.png)

<details>
  <summary>Wallpaper selection in EasyRPG Player (0.6.2.3):</summary>
  
![Screenshot_2021-05-03_18-47-36](https://user-images.githubusercontent.com/64451846/116953100-3fe8b880-ac41-11eb-9c2d-52bac4912ae5.png)
![Screenshot_2021-05-03_18-49-38](https://user-images.githubusercontent.com/64451846/116953104-41b27c00-ac41-11eb-85a6-143588b2f7ba.png)
</details>

Wallpaper selection in EasyRPG Player (Continuous build downloaded on May 3rd 2021):
![Screenshot_2021-05-03_19-39-39](https://user-images.githubusercontent.com/64451846/116955557-c30d0d00-ac47-11eb-8f0f-f4c4c4ccaab3.png)

#### Describe the issue in detail and how to reproduce it:
~~In EasyRPG Player the wallpaper selection screen of Yume2kki doesn't show the image preview in the background, in RPG_RT you can see a preview of the wallpaper before setting it.~~ (Only applies to Player version 0.6.2.3 and earlier)

In Yume2kki 0.116 the wallpaper selection screen is supposed to have a faded preview of the wallpaper you're about to select in the background, in EasyRPG Player the fade effect doesn't show.

For whatever reason the fade effect _does work_ in earlier versions of 2kki in Player. (The wallpaper selection UI is _slightly_ different in 0.116 compared to earlier versions so 2kki's developers must of made some change that isn't compatible with Player yet)

Also, the wallpapers have a white outline arround their thumbnail that doesn't show up in Player. (Regardless of 2kki's version)

To reproduce: Start a new game or load a save, head over to the computer, select tools, and just keep pressing Z until you reach the wallpaper selection screen. 

(Very sorry if this turns out to already be fixed in some branch! Or if it turns out this is a duplicate...)

EDIT: Here's an image of RPG_RT, RPG_RT with an extra colors patch, and EasyRPG Player side by side:

![rpg color differences](https://user-images.githubusercontent.com/64451846/116964115-8fd67800-ac5f-11eb-9f98-8575da75f80e.png)

**Comment by purupurupuruin** [comment] 2021-05-04 02:43
![Screenshot_2021-05-03_19-39-39](https://user-images.githubusercontent.com/64451846/116955557-c30d0d00-ac47-11eb-8f0f-f4c4c4ccaab3.png)

Agh, I'm an idiot, just tested it with the continuous build and the background 
preview is there, however the outlines around the thumbnails is still missing so it's still a bug? (I think?)

**Comment by Ghabry** [comment] 2021-05-04 05:25
This is definitely a bug but I'm afraid that this is almost impossible to figure out because the computer in yume2kki is a mess.
I wonder when the music room will break again 😅

**Comment by purupurupuruin** [comment] 2021-05-04 06:13
So I noticed something else different when looking at the comparison screenshot:
![rpg grid diff](https://user-images.githubusercontent.com/64451846/116966437-0b86f380-ac65-11eb-83e0-29d8bf90a18b.png)

Somehow the thumbnail for the 2nd wallpaper is different looking in Player, like some kind of positioning issue?

**Comment by Ghabry** [comment] 2021-05-04 07:40
The question mark also looks different. I would say they simply draw the question mark image twice. Once normally and then once below with a 1 pixel offset to get a drop-shadow effect.

**Comment by purupurupuruin** [comment] 2021-05-04 09:09
Oh forgot to mention this here, but on the IRC channel I mentioned that the irrelevant UI change in the newer versions of the wallpaper selection screen is just the computer's taskbar remaining visible (In older versions of 2kki the taskbar disappears when browsing the wallpaper list), it _might_ be related since that's the only thing that's noticeably different about selecting a wallpaper.

**Comment by Ghabry** [comment] 2021-05-05 19:28
Honestly no idea how they draw the question mark.

The image is this one which looks exactly how our Player renders it.

They use a 10% zoom so there could be a scaling difference but how do they even get the left and top border? They are not part of the image!

![pc yumegamen 03_？](https://user-images.githubusercontent.com/1331889/117198009-c4297000-ade8-11eb-87ec-a5a9c699d4fc.png)

**Comment by Ghabry** [comment] 2021-05-05 19:58
The background is something stupid again:

The effect is applied by using a 30% transparent black picture (■.png) with Pic ID 2. Afterwards they create another Picture at ID 2 that has _no filename_.

We reject such pictures and delete the one allocated to the ID. This means the black picture is gone. When it is rejected and the old not deleted the effect works :facepalm:

**Comment by purupurupuruin** [comment] 2021-05-05 20:02
I don't get why the 2kki devs didn't just have the question mark image file look how it looks ingame instead of doing something weird to somehow render it completely differently

**Comment by Ghabry** [comment] 2021-05-05 20:06
Really no idea how the scaling algorithm of RPG_RT works (likely GDI based?). Somehow that small gray line at left and top keeps its size while the big one right and bottom shrinks. ¯\_(ツ)_/¯.

**Comment by purupurupuruin** [comment] 2021-05-05 20:09
It's like they somehow move pixels from the bottom and right to the top and left.

Like how in some classic arcade games you move past the boundary of the screen and end up at the other side somehow.

**Comment by Ghabry** [comment] 2021-05-05 21:11
The scaling is obviously not nearest neighbor with the most common pixel winning. Instead it is "top left corner".

For the 320x240 to 10%. This means it is 32x24, so "10 pixel per segment".

This means for the top-left pixel it looks at "0x0", for the next at "10x0" etc. When you just set this one single pixel it uses this color.

Here is my modified question mark image: When you rescale this to 10% in RPG_RT and display it the pixels are transparent (that color is palette index 0)

![pc](https://user-images.githubusercontent.com/1331889/117209651-ecb86680-adf6-11eb-8421-23a3fc445b05.png)

![bla](https://user-images.githubusercontent.com/1331889/117209808-29845d80-adf7-11eb-8471-e921ce99fbd8.png)

**Comment by rueter37** [comment] 2021-05-09 17:14
@Ghabry: Your approach should work with the RPG Maker 2003 battle gauges as well. But telling pixman to scale the images that way is near impossible due to documentation not existing...

**Comment by carstene1ns** [comment] 2022-04-24 16:32
One part of this bug has been fixed in 0.7.0. Closing as the rest is a duplicate of #446.

@purupurupuruin Thank you for the extensive testing!

**Closed by carstene1ns** 2022-04-24 16:32 UTC
Labels: Duplicate, Pictures
