### ISSUE TITLE
The game audio is lost when it switch from headphones to loudspeakers and can only be closed by force.

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#1596] opened 2019-01-02 18:28 UTC
**Tested in**: Player 0.5.4 (continuous).

**Bug**: The issue is that once the audio is changed from headphones to speaker, the game is completely muted and the console throws cumulative sound errors.

E.g. I start playing with loudspeaker and everything is fine.
I change to headphones and everything is fine, If I disconnect headphones I already have the error.

Then, when I want to close the game (Alt + F4 or from window mode), it stays frozen and there is no other way to force closure.

**Platform**: Windows 7 (x64) and sound card NVIDIA.

![audio_bug](https://user-images.githubusercontent.com/18174790/50605049-59d32e80-0ec1-11e9-8b0e-ce0e22238ef6.png)

**Video**:
[![](http://img.youtube.com/vi/SSMD2CLbGxk/0.jpg)](http://www.youtube.com/watch?v=SSMD2CLbGxk "")

**Log**: [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/2721479/easyrpg_log.txt)

**Comment by elsemieni** [comment] 2019-01-02 19:54
A similar issue reported in SDL forums, probably related with SDL2_Mixer https://discourse.libsdl.org/t/windows-7-update-messing-with-sdl2-mixer/21271

**Comment by Ghabry** [comment] 2019-01-02 20:36
Are we talking about USB-Headphones here or a cable connected to the headphone jack of your soundchip?
I would assume this is only a problem with the USB-case as this introduces a new audio device, the headphone jack is a device-driver feature which uses the same audio output (at least on my systems).

Could be also tested if attaching a HDMI-device that supports audio (TV display) introduces the same problem.

**Comment by fmatthew5876** [comment] 2019-01-03 01:54
In particular, it would be good to know if the audio device changed. In Windows 10, you can just click on the volume icon and see what audio device is currently being used. 

Sometimes headphones/speakers are same device and sometimes different devices.

You said the audio is "Nvidia". Is that digital audio over hdmi / displayport from a GPU? In that case most certainly the headphone output is a different device.

**Comment by elsemieni** [comment] 2019-01-03 03:39
New clues:

- This bug triggers in Windows 7 when you disable/disconnect the current audio device (no matter if you re-connect it later). It starts show audio channel warnings and it hangs when it closes.
- Also in Windows 7 and 10 (maybe more? Didn't test more Windowses) if you try to run player (tested with 2nd Jan nightly) with no audio interfaces, Player closes instantly and this error is in the easyrpg_log:

`[2019-01-03 00:14:45] Error: Couldn't initialize audio mixer.
WASAPI can't find requested audio endpoint: No se ha encontrado el elemento.`

That spanish text can be translated to `Couldn't find element`.

All the above was tested with Player Nightly (Jan 2th) and our custom build (using windows toolchain -> SDL 2.0.9 and SDL2_Mixer 2.0.2).

Maybe this can be related with https://github.com/EasyRPG/Player/issues/1405 somehow, but I'm not sure...

**Comment by fdelapena** [comment] 2019-06-10 18:18
Possibly related fix in SDL2 mercurial repository, it is suggested to get a build and test yourselves:
http://hg.libsdl.org/SDL/rev/bfd1b2fc6e2f

**Comment by elsemieni** [comment] 2020-01-03 00:45
Tested with custom build (lastest git) Windows ~ SDL 2.0.10-2 (vcpkg), in Win7 SP1, same envoriment as https://github.com/EasyRPG/Player/issues/1596#issuecomment-451049389 (remember the original problem does not reproduce in >=Win8). 

Now Player behaves normally when an audio device is removed. No warnings are shown when audios are played in this scenario. Player closes correctly at exit.  

Seems the problem was fixed.

**Comment by carstene1ns** [comment] 2020-01-05 14:33
Might be a fix in SDL/SDL_mixer. Closing.

**Closed by carstene1ns** 2020-01-05 14:33 UTC
Labels: Audio, Building, Needs feedback, Patch available
