### ISSUE TITLE
F-droid build is outdated

### ISSUE THREAD

**Issue by Thewisem** [EasyRPG/Player#2552] opened 2021-06-05 15:05 UTC
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
The fdroid build is behind the play store build. Please fix that

**Comment by Ghabry** [comment] 2021-06-05 16:16
Sorry there is nothing to fix here.

We sometimes abuse the users on the play store for beta testing because to get enough test coverage before doing an official release.

Use a continuous build from our website or wait for 0.7. (ETA July)

**Comment by Thewisem** [comment] 2021-06-05 18:20
Ooooohhhh That is soo wrong out of context

**Comment by BlisterB** [comment] 2021-06-06 17:00
I think he was talking about : https://f-droid.org/fr/packages/org.easyrpg.player/

**Comment by fdelapena** [comment] 2021-06-06 17:07
Yes, and the current stable version is 0.6.2.3, the same as in f-droid, while Google Play uses development snapshots when needing massive testing for regressions.

**Comment by Ghabry** [comment] 2023-07-28 11:25
There is a lack of maintainers for the fdroid-port unfortunately.

**Comment by Ghabry** [comment] 2023-09-13 20:11
closing this as there is a 2nd issue for this.

**Closed by Ghabry** 2023-09-13 20:11 UTC
Labels: Android, Building
