### ISSUE TITLE
Yume2kki: Scrolling white line in foggy areas.

### ISSUE THREAD

**Issue by purupurupuruin** [EasyRPG/Player#2200] opened 2020-05-05 23:15 UTC
#### Name of the game:
Yume2kki

#### Player platform:
Linux

#### Attach files (as a .zip archive or link them)
[video_comparison.zip](https://github.com/EasyRPG/Player/files/4584105/video_comparison.zip)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4584089/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
In The Docks area of 2kki ~~the fog coloration is off and~~ there is a weird moving white line showing every few seconds, I've attached a video comparison of EasyRPG and RPG_RT.
EDIT: The white line bug also shows during the "March of Progress" event in Chess World. (That area is harder to reach though.)

To reproduce:
Head to The Docks
Unfortunately due to the nature of the game you need a guide to get anywhere.
https://yume2kki.fandom.com/wiki/The_Docks
EDIT: Or trigger the March of Progress event in Chess World https://yume2kki.fandom.com/wiki/Chess_World

(The EasyRPG side unfocused a few times so it pauses,~~I wish I could disable pause on unfocus!~~)
> Config option for this is planned

Thanks!

**Comment by Ghabry** [comment] 2020-05-05 23:47
> weird moving white line

That's really a bug.

> fog coloration is off

This is likely caused by the color difference: RPG_RT renders in 16bit (65k Colors) and we render in 24bit (16 Mio. Colors). 

See #1249. We don't consider such color differences bugs.

> The EasyRPG side unfocused a few times so it pauses, I wish I could disable pause on unfocus

Config option for this is planned

**Comment by Ghabry** [comment] 2020-05-05 23:53
btw thanks for playing through Yume2kki for us!

There is no known way left to freeze the game in Player but I'm curious if you will find an event the breaks the Player again :).

By now it is only visual and audio glitches. Good news.

**Comment by purupurupuruin** [comment] 2020-05-06 00:58
You're welcome! If I find any crashing bugs I'll definitely report it, now that I have a VM running I have a better idea of what's a bug and what isn't.

Also added another example I found of this bug, in Chess World, just in case adding an additional example helps.

**Comment by purupurupuruin** [comment] 2020-05-06 04:45
So after random exploring I've found another area where the white line appears, Rusted City, I'm guessing the line appears everywhere that's foggy in 2kki.

**Comment by Ghabry** [comment] 2020-05-06 11:33
Btw when you are using Linux you can start the game in "TestPlay" mode. Either run it from the editor or with command line argument "TestPlay". Then you can open a debug menu with F9 that offers a "Save" option.
Makes it easier for us to reach the location when there is a save nearby :)

**Comment by purupurupuruin** [comment] 2020-05-06 18:59
[fogglitchsaves.zip](https://github.com/EasyRPG/Player/files/4588901/fogglitchsaves.zip)
Here's 3 saves, one before the teleporter to The Docks, one before the throne room and March of Progress event in Chess World, and one before the ladder to Rusted City, all 3 areas have the fog glitch.
As stated in #2199, the version of the game I used is 0.112.

**Comment by Ghabry** [comment] 2020-05-06 21:02
My guess is that the picture rendering is off-by-one pixel here. (floating point rounding error?)

The event does stuff like (Picture17 is 640x480)
```
@> Show Picture: 20, '20_Picture_17', (0,120), 100%, 50%, M6
@> Show Picture: 21, '20_Picture_17', (640,120), 100%, 50%, M6
@> Move Picture: 20, (-320,120), 100%, 75%, @10.0s
@> Move Picture: 21, (320,120), 100%, 75%, @10.0s
```

So when this is misaligned by one pixel one line will overlap and add up to 100%.

**Comment by purupurupuruin** [comment] 2021-05-04 08:55
Since the debug save is from an older version I made a newer one just in case, this save was made in 0.116 of 2kki.

[docks save.zip](https://github.com/EasyRPG/Player/files/6419974/docks.save.zip)

(This save is just before the docks, just interact with the portal)

**Comment by Ghabry** [comment] 2021-08-07 21:00
this is likely a duplicate of #446  . as observed by rueter there is a of-by-one pixel calculation when scaling.

**Comment by carstene1ns** [comment] 2022-04-24 16:26
Closing as duplicate.

@purupurupuruin Thank you for the save files that make this easily reproducible!

**Closed by carstene1ns** 2022-04-24 16:26 UTC
Labels: Duplicate, Pictures, Settings
