### ISSUE TITLE
3DS: \>\C[?] string showed before dialog text

### ISSUE THREAD

**Issue by pdapanda** [EasyRPG/Player#849] opened 2016-03-26 16:33 UTC
EasyRPG was recently ported to 3DS, when it shows dialog or other texts,there is \>\C[0] or something ahead of it.
http://gbatemp.net/attachments/scr_24_combined-png.43647/
http://gbatemp.net/attachments/scr_28_combined-png.43659/

**Comment by Rinnegatamante** [comment] 2016-03-26 16:59
3DS buils has not yet officially released, you should perform the same bug on an official release (PC, Android, Web, Wii) before opening an issue i think.

**Comment by Ghabry** [comment] 2016-03-26 17:47
Please test with an official version (see the download section of the website).

Which game is that? How to reproduce?

**Comment by carstene1ns** [comment] 2016-03-27 10:42
According to [this](http://gbatemp.net/threads/easyrpg-3ds-rpg-maker-2000-2003-player-for-3ds.419889/page-4#post-6202472), the game is "Grimm Adventures".
You can use this save to skip the intro: [Save01.zip](https://github.com/EasyRPG/Player/files/190867/Save01.zip)
![1](http://picload.org/image/wwlrogg/screenshot_1.png) ![2](http://picload.org/image/wwlrogd/screenshot_2.png)

**Comment by Ghabry** [comment] 2016-03-27 12:50
Nice 3D rendering btw

**Comment by fdelapena** [comment] 2016-03-27 13:20
This one remembers #460, but maybe is unrelated.

**Comment by Ghabry** [comment] 2016-03-27 13:51
I think the download link for Grimms Adventure is 404

**Comment by Zegeri** [comment] 2016-03-27 14:09
Mirror:
https://mega.nz/#!9whAnR7R!A4D298UlkGpYHAtes5hG-MpSv5bnXwBjtvuGAu_Lv4I

**Comment by Ghabry** [comment] 2016-03-27 14:25
Closing as a duplicate of #460

**Closed by Ghabry** 2016-03-27 14:25 UTC
Labels: Window/Scenes
