### ISSUE TITLE
Battle End plays title screen music when map has no BGM

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2411] opened 2020-10-25 20:34 UTC
Create a game which has a title BGM and a map with no BGM.

Start a new game, and then start and finish a battle.

After the battle finishes, the map will play the title screen music.

**Comment by rueter37** [comment] 2020-12-12 14:58
I cannot reproduce this if the map without BGM has the option `music_type` set to 2 (Specify), so this works as intended. But it occurs if the map without BGM has the option `music_type` set to 0 (Same as Parent Map) or 1 (Event Setting) and none of its parent maps has any BGM explicitly set with the option `music_type` set to 2. In this case it looks like it takes the title screen as the "ultimate parent map" and uses its music then.

**Comment by rueter37** [comment] 2021-09-04 15:46
A possible fix for this one is adding `data.current_music.name = "(OFF)";` [after line 127 of game_system.cpp](https://github.com/EasyRPG/Player/blob/master/src/game_system.cpp#L127). I did not open a PR with this change because while it seems to work, there is a high likelihood that this will break something else.

**Closed** 2021-09-09 02:03 UTC
Labels: Audio, Patch available
