### ISSUE TITLE
Menu button not working under Android possibly after setting target SDK 12

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#442] opened 2015-03-23 03:26 UTC
Though both software menu (from the on screen button bar) and hardware menu button are available on the tested Android 3.2 device, neither of them are working This happens at least since recent 0.2.2 updates. Show FPS and other in-game options are not accessible. Targetting SDK 12 is needed to have USB/Bluetooth keyboard/joystick support from SDL2.

New menu option added by @BlisterBoy shows the "Change the default button mapping" from hardware button properly, however it is not possible to use the hardware button to add, modify or save options due to the same issue, making impossible to set them from the device.

I guess it is somewhat related with [this behaviour](http://techblog.rokoder.com/android-missing-menu-button/).

Maybe adding a hidden action bar for these activities could fix the button issue for Android < 4.x.

**Comment by BlisterBoy** [comment] 2015-03-23 08:16
Hum I'm trying to obtain the same issue but everything was alright on my tests, do you use a VM or a real device for your tests ?

**Comment by Ghabry** [comment] 2015-03-23 09:25
Maybe render a hamburger icon (≡) in the top-right corner that triggers that menu... Most newer apps have such an icon.

**Comment by fdelapena** [comment] 2015-03-23 12:41
The hamburger or triple vertical dot icon is shown already for the menu option added and it works, I can use the hardware button and opens it. I use a real Android 3.2 device.

**Comment by Ghabry** [comment] 2015-03-23 12:42
Soo is it now broken or working? :)

**Comment by fdelapena** [comment] 2015-03-23 12:51
I mean only works for the menu which shows the "Change the default button mapping menu item. It does not work for the in game menu (show fps and such) and for the menu in the button layout for the add, save and such options.

**Comment by BlisterBoy** [comment] 2015-03-24 00:42
OOoookay I was not sure but now I understand that you're facing a problem I had when I was developping the button mapping system on a test project working with SDK 20. The problem was solved when I downgraded the SDK.

The GameBrowser's menu works because it's a type of Activity displaying an action bar (the menu is automatically place in it).
When you use a simple Activity, Android seems to act differently depending on the API (surely because of the successive modifications of Android GUI Mantras). I'm not sure at 100% but placing a menu icon doesn't seems to be wanted by Google (no mention in http://developer.android.com/guide/topics/ui/menus.html and I never saw this on another app).

I'll try to solve the problem, but if I don't find a solution I can use a trick I saw on a lot of emulators : use the back button to display the menu
Pro:
:+1: Compatible with all API, no more problem for now and ever
:+1: We can't decently use an action bar on Player and Button Mapping System (ergonomic purpose)
:+1: That was already on the Button Mapping System to-do list (to prevent an exit without saving, that fooled me a lot of times)
:+1: Simplification of user's experience

**Comment by BlisterBoy** [comment] 2015-03-24 14:24
@fdelapena after many attempts I didn't success on reproducing the bug, do you want me to implement the behavior described in the previous comment ?

**Comment by fdelapena** [comment] 2015-03-24 14:39
According with [this blog entry](http://android-developers.blogspot.com/2012/01/say-goodbye-to-menu-button.html), there are devices without menu button, so looks fine the back button approach :+1:
> Android no longer requires a dedicated Menu button, some devices don’t have one, and you should migrate away from using it.

Let's kill the menu button then ^^

**Comment by BlisterBoy** [comment] 2015-03-24 14:48
Ookay, this will be done this week !

**Comment by BlisterBoy** [comment] 2015-05-11 09:46
Hi guys !
Please excuse me I have a large amount of college work to deal with, I don't think this issue will be fixed for this milestone.
But after June the 5th I'll be free and I intend to seriously learn Android, Easy RPG will benefit of this work :).

**Comment by Ghabry** [comment] 2015-05-11 12:01
Oh great that you havn't left us. Take your time

**Comment by BlisterBoy** [comment] 2015-05-11 12:08
Of course I've not left you :p.
The rm scene is currently really exciting, I'm sure Easy RPG has its part in the recent official release of RPG Maker 2003 (12 years after the japaness release !! Wow). French community is pretty excited about the project and is waiting for the program to support advanced features.
Actually everyone wants this game on Android hahaha : http://www.aedemphia-rpg.net/screenshots.html )

When my exam will be finished I intend to improved the Android users experience (no more screen saving during game, possibility of changing the EasyRPG directory project, improvement of the button mapping system and of course fix the Android opened issues :) )

**Comment by Ghabry** [comment] 2015-05-11 12:20
Wow this game looks amazing! Is that really a RPG Maker 2000 game??
I'm not sure if we are really one of the reasons for the re-release ;). But I know that one German person (Cherry) is involved who reverse engeneered most parts of the RPG Maker (maybe you heard of DynRPG before). The sourcecode of RPG2k3 was lost (this is good for us, makes adding new features for them more difficult :D) so they can only apply binary patches.

The 0.3-release is scheduled for today or tomorrow. There are two urgent bug fixes pending (Save corruption and battle chars not rendered). And the blog post must be written :D. I will add a note then that improved Android support comes with a later update.

**Comment by BlisterBoy** [comment] 2015-05-11 12:35
Yep this is a Rpg maker 2003 game, and it's awesome ;).
We know Cherry :), his patchs are really often used in our community (specially for skipping the title screen). But DynRPG didn't found the succes in our community (big buzz at the beginning, but nothing after).

We are in discussion with Cherry and he seems to not know when is collaboration with Enterbrain will be over, but he don't think that big improvements will be implemented as you said.
However, the big features that french community wants are not really big : 
- Skip the title screen (I suppose a line in the .ini for Eeasy Rpg Player could be enough, with informations about the switch involved in the display of the loading/saving screen)
- Support of more than 256 colors and alpha transparence (for light effect and photoshopped panoramas), I don't know if the Player is already ready for this but as we have the source code it wouldn't be hard.

Imho the second point would be the features that would make Easy RPG really really attractive. I'm convinced that in few month, people will use RPG Maker Editor for creating the game, and Easy RPG Player for playing it in the train (that's what I'm already doing ;) ).

**Comment by Ghabry** [comment] 2015-05-11 12:42
DynRPG is a nightmare for us. So it's good when it isn't used ;).
Yeah he said that a custom title screen is on his todo list... let's see what happens.

32bit is already fully supported for PNG, including alpha channel (there was no obvious reason to limit this)

Well we lack developers for editor but our Player is still improving. There are tons of bugs... but it makes progress :D. I think for 0.3.1 I will target the battle system again which is still far away from being perfect.

**Comment by BlisterBoy** [comment] 2015-05-11 12:52
Excellent news for the 32bits support ! Thanks for the informations !

Be ready for June haha. After my exams I intend to start communicating with french community, some of them they are extreeeeeemely meticulous, if the project interests them I think a large amount of bug will be found in few months.
I also expect that graphic designers and musicians will help for RTP Replacement project (all the music of Aëdemphia are made by the community, they are really talented : http://www.rpg-maker.fr/index.php?page=forum&id=22052 ). 
I'm already in contact with the developper of Aedemphia (the owner of the biggest website relative to RPG Maker) and he would be happy to help the project by giving him visibility which is a good thing even if our community is a microcosm after all :p.

**Comment by BlisterBoy** [comment] 2015-07-04 19:42
Hi everyone

Just to know @fdelapena , if you increase the API, does menu button still don't work ?

**Comment by fdelapena** [comment] 2015-07-04 20:35
@BlisterBoy I've updated the tablet to Android 4.x some weeks ago and now hardware buttons work. I could try to downgrade the device again for testing if needed, but i guess back button for menu is still worth for devices without menu button.

**Comment by BlisterBoy** [comment] 2015-07-05 08:58
You lost me xp.
The problems was the menu hardware/software buttons that didn't work, right ??

**Comment by fdelapena** [comment] 2015-07-05 09:11
Oops, yes, I was meaning the menu button, sorry. The back button always worked.

**Comment by BlisterBoy** [comment] 2015-07-05 11:51
Okay :) !
Sooo it seems that the problem came from your previous android rom. I'll let the software button, and call the menu when the user press back, to avoid to exit a game by error or exit the button mapping system without saving.

**Comment by BlisterBoy** [comment] 2015-07-17 09:21
I think this issue can be closed :).

**Closed** 2015-07-17 13:35 UTC
Labels: Android, UX
