### ISSUE TITLE
Incorrect battle behavior in Shitigadianzu

### ISSUE THREAD

**Issue by RyutheXIIIth** [EasyRPG/Player#1412] opened 2018-09-03 15:25 UTC
#### Name of the game:
Shitigadianzu (City Guardians)

#### Player platform:
Windows (Windows 7 64-bit), Android (Android Nougat 7)

#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/2346014/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
The game doesn't seem to work as intended in EasyRPG for Windows and Android, tested with the latest continuous builds. The monsters are supposed to be able to attack the player and also fill up the yellow bar while they are down, but they seem unable to. Only the octopus pet seems capable of filling it up. Also, the player should not be able to access the menu screen while they are down. It should only be accessible once the player is released.

**Comment by Ghabry** [comment] 2018-09-03 16:03
Thanks for the bug report.

Could you provide a download link for the game?

Does the game use a the default RPG Maker 2000/2003 battle system or a custom battle system? According to the logfile it should be custom.

**Comment by RyutheXIIIth** [comment] 2018-09-03 16:31
The game is hard to come across, and I found it on a thread in ulmf. Here's a direct link to the game:
mega.co.nz/#!boI0WSrK!16FgVnyxUwwzaIoDhMWqnU6MK9ixJ2VRtQgpv1vUYn4

And indeed, it uses a custom action-oriented battle system, similar to VH01.

**Comment by Ghabry** [comment] 2018-09-03 22:32
> the player should not be able to access the menu screen while they are down
This will be fixed as part of #1404

The other part is hard to figure out because the event code is really complicated and I have no idea which part of the code is important.

Variable 76 controls the bar but no idea how the incrementing works.

**Comment by RyutheXIIIth** [comment] 2018-09-04 03:03
If it helps, I can narrow down the case when the bar actually fills later today, by running it in RPG_RT.

**Comment by Ghabry** [comment] 2018-09-04 10:34
It would help if you could figure out which event is responsible for assigning to Variable 76 while the heroine is "down". I already tried yesterday for one hour to do this but wasn't able.

**Comment by RyutheXIIIth** [comment] 2018-09-04 10:46
I'd like to help, yes, but I have little idea to go about doing that. Anywhere I can start?

**Comment by RyutheXIIIth** [comment] 2018-09-04 14:06
Do you need the specific event numbers?

**Comment by Ghabry** [comment] 2018-09-04 14:10
I didn't knew about this dumping tool yet, useful and I see some increments of Variable 0076 there, maybe it helps me to figure it out. thanks!

**Comment by RyutheXIIIth** [comment] 2018-09-04 14:31
Found the tool here if you want it:
http://vgperson.tumblr.com/post/83749711667/so-you-want-to-translate-an-rpg-maker-20002003

**Comment by Ghabry** [comment] 2018-09-04 18:17
Variable 202: Contains the ID of the enemy that is currently pleasuring the heroine

The enemy stuff begins on event touch, assigning 202 and invokes Common Event 214.

Then this calls on line 8 common event 50 which does the incrementing of the enjoyment progress bar at line 13.

**Comment by Ghabry** [comment] 2018-09-04 18:36
Seems that Hero State (V21) never becomes >= 7

**Comment by Ghabry** [comment] 2018-09-04 22:06
The problem something completely different: When the heroine is down touch triggers don't execute anymore because of the ``if (Main_Data::game_player->IsInPosition(x, y) && !Main_Data::game_player->IsBlockedByMoveRoute()) {`` check. When removing "IsBlockedByMoveRoute" it works.

This was the fix for #687 but I can't reproduce this bug even after deleting the check... Was properly fixed somewhere else?

**Closed** 2018-09-30 16:54 UTC
Labels: Event/Interpreter, Patch available
