### ISSUE TITLE
Play SE (OFF), instead of stopping sounds, does nothing

### ISSUE THREAD

**Issue by vgperson** [EasyRPG/Player#1355] opened 2018-05-06 07:07 UTC
#### Name of the game:
Witch's Heart (http://vgperson.com/games/witchheart.htm)

#### Player platform:
Windows

#### Attach files (as a .zip archive or link them)
[WitchsHeartSEStopBug.zip](https://github.com/EasyRPG/Player/files/1977412/WitchsHeartSEStopBug.zip)

#### Describe the issue in detail and how to reproduce it:
When Play SE is told to play "(OFF)", EasyRPG treats it as a do-nothing command, but this is not the case; it's actually supposed to stop all sounds that are playing. This often causes noticeable issues in Witch's Heart, which will play rather lengthy sounds and use this command to stop them - in EasyRPG, they just keep playing until the sound finally finishes. The save shows this issue during cooking, where the sizzling sound will continue long after you stop the flame.

There's already an "Audio().SE_Stop()" used when returning to title to stop all sounds, so this should be an easy fix.

**Comment by Ghabry** [comment] 2018-05-06 08:52
Thanks for the report.

We are already aware of this bug. Closing this as a duplicate of #1120.

**Closed by Ghabry** 2018-05-06 08:52 UTC
Labels: Duplicate

**Comment by Ghabry** [comment] 2018-05-06 10:08
Btw is this just my eye vision or does the color between the reference picture of the perfect meat and the real meat don't really match?

Luckily there is an extra indication.
