### ISSUE TITLE
BGM MIDIs playing at full volume regardless of the "BGM volume" setting.

### ISSUE THREAD

**Issue by CortexReaver** [EasyRPG/Player#3242] opened 2024-06-25 12:44 UTC
So, If you run this game: https://www.glorioustrainwrecks.com/node/11012
The BGM midi in the main menu can be played only at two states: maximum loudness (volume from 1% to 100%) and disabled (volume at 0%).
But, I've opened the midi files with an MPC player and it behaves exactly the same. Can it be just win 10/codec bug?

similar bug: https://youtu.be/WGR_6lqkDgk (ver. 2024-06-11)
no matter what I set (sound and\or music) BGM is 100% loud.

I've used the nightly build from here: https://ci.easyrpg.org/view/Player/job/player-win64/

![25-06-2024 233844](https://github.com/EasyRPG/Player/assets/34350690/3c1af327-39b4-46de-81f2-141eda7978eb)

Maybe it is not a latest 64 bit windows version? Hmm. Who knows!🤔https://youtu.be/qYo8KaL5Ijc

OS: Windows 10 Pro 22H2 build 19045.3448
K-lite codec pack was also installed on the system
Virtual Cables (https://vb-audio.com/Cable/)
Ear Trumpet (https://community.chocolatey.org/packages/eartrumpet#install)
Micswitch(https://github.com/iXab3r/MicSwitch)
OBS for the recording
Ugreen USB DAC was used

**Comment by Mimigris** [comment] 2024-06-25 12:59
Hello. When doing reports, make sure to use the latest continuous build rather than the latest stable version, as some bugs could have been fixed since. This issue has normally been fixed in the continuous build of the Player (available on our site at the bottom of the downloads page), I cannot reproduce it on my side, so could you recheck this problem by instead using the continuous build?

**Comment by CortexReaver** [comment] 2024-06-25 19:14
Yes, I used the nightly build from here: https://ci.easyrpg.org/view/Player/job/player-win64/
Probably something to do with my OS then, hm

**Comment by CortexReaver** [comment] 2024-06-25 19:25
Here's another: https://rpgmaker.net/games/3390/?post=300519
Don't know if this is an issue on my side again, but it behaves differently: no matter what I set (sound and\or music) music is 100% loud.
proof: https://youtu.be/2zEFKhAMUkI

**Comment by Mimigris** [comment] 2024-06-25 19:34
I cannot test this game due to RPG Maker dot net currently having redirection issues making it unable to be accessed on my side, but what you show is the expected scenario on the version 0.8.0: could you verify by going in License and selecting EasyRPG that your version of the Player is from 2024-06-11 rather than being listed as version 0.8.0?

**Comment by CortexReaver** [comment] 2024-06-25 19:46
Here you go: https://youtu.be/WGR_6lqkDgk

**Comment by Mimigris** [comment] 2024-06-25 19:51
I'm very sorry to not have specified that properly, but you need to press Enter while selecting EasyRPG Player in the License menu, this displays a screen with the version of the engine, which is what I'm looking for.
![image](https://github.com/EasyRPG/Player/assets/108797333/6d10086f-fbdc-4ec9-ae7b-67331f5ea982)

**Comment by CortexReaver** [comment] 2024-06-25 19:52
rewind video to the end, I have showed it there.

**Comment by CortexReaver** [comment] 2024-06-25 19:58
https://youtu.be/UZX1JE5v1jw

**Comment by Mimigris** [comment] 2024-06-25 20:00
Ah, didn't saw it due to being displayed for only half a second, that seems to be indeed the current continuous build and the same than the one I shown.
I suppose that it could depend on the hardware/midi drivers so it may require additional feedbacks, since I cannot reproduce this at all on my side.

**Comment by CortexReaver** [comment] 2024-06-25 20:07
@Mimigris I've edited topic, what else info can I provide?

**Comment by Mimigris** [comment] 2024-06-25 20:21
I suppose maybe MIDI drivers, and confirm if you're indeed on the Windows 64 bits version of the Player to be sure of the version. Unfortunately I'm no MIDI expert so I'm afraid that I cannot help further than that.

**Comment by CortexReaver** [comment] 2024-06-25 20:30
Where can I see the midi drivers on win 10? Did I need to install them from somewhere?

**Comment by Ghabry** [comment] 2024-06-25 21:36
Is the volume of the midi also messed up when using RPG_RT? We use the same interface so it should be broken the same way.

**Comment by CortexReaver** [comment] 2024-06-25 22:07
The original RPG_RT doesn't have volume adjustments...
Or maybe there is a specific version that I am unaware of.

**Comment by Ghabry** [comment] 2024-06-25 22:27
Oh sorry I didn't read properly. Thought it's broken in-game. You mean the volume setting for the bgm.

Yes this is not implemented yet in the continuous build. See also #3083 

This will be fixed soon because we have a pending pull request for this.

**Comment by Ghabry** [comment] 2024-07-01 19:49
closing as dupe of #3083  which should be fixed now

**Closed by Ghabry** 2024-07-01 19:49 UTC
Labels: Duplicate, MIDI, Settings
