### ISSUE TITLE
The Gray Garden: Custom menu arrow keys don't work 

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2441] opened 2021-01-14 20:03 UTC
This issue seems to be a regression. It happens in current stable and master versions.

Since version 1.08, this game features a custom menu for quick access to save and quit.
After skipping intro (slightly long, better use fast forward keys), the custom menu will appear with the cancel key, but arrow keys don't allow to select other options.

Emscripten tests:
https://easyrpg.org/play/?game=the_gray_garden
https://easyrpg.org/play/master/?game=the_gray_garden

**Comment by Ghabry** [comment] 2021-02-08 15:41
Will mark this as a dupe of #2294 
Again engine detection problem, works with engine=rpg2k3e

**Closed by Ghabry** 2021-02-08 15:41 UTC
Labels: Event/Interpreter, Regression
