### ISSUE TITLE
Idea for the Android port

### ISSUE THREAD

**Issue by BlisterB** [EasyRPG/Player#575] opened 2015-09-07 11:59 UTC
Hi guys !

I open this issue to centralize suggestions about how improve the Android port, don't hesitate to give me job :) !

Idea : 
- [x] Multiple game directory
- [ ] Hi res splash screen while game browser parses the directories (I think this one is not possible has it depend from the C++ code)
- [x] Thumbnail support in GameBrowser (ask to find a quick way to store title screenshot)
- [ ] Key mapping for gamepads
- [x] Better configuration file for projects
- [x] Re do the settings activity
- [x] Different game displaying system depending on device screen
- [ ] A setting button in "select game layout"
- [ ] Ask for permission to add .nomedia in new game folder.

**Comment by Ghabry** [comment] 2015-09-07 12:10
- Support for multiply game directories (configurable in the settings)
  - The Game Browser itself should just merge all directories
  - Problem: How to deal with duplicates (same game in multiple directories)
  - Problem: On some Android devices (Android 4.4) the SD card is without rooting only writable by system apps (= only google)
     - Workaround: New command line option --save-path to overwrite the save directory (and save in the data directory of the apk instead). This should be transparent for the user, no interaction required.
- Button mapping for individual games
 - Reasonable defaults for RPG2k and RPG2k3 and some popular games, e.g. Yume Nikki preset
 - Moving buttons around while ingame (with running game rendered semi-transparent in the background)
 - Resizing of buttons
- A shiny, high-res "Easy RPG Player" splashscreen while the game browser parses the directories ;)

I don't think that file management (delete game e.g.) is required, but maybe "open game directory" and "open save directory", which launches ES File Explorer or whatever is installed.

**Comment by BlisterBoy** [comment] 2015-09-07 16:16
Thanks for the ideas :) ! I'll start to improve the button mapping system (the easiest xp). I think I'll switch to an xml format, that will be way more flexible for the futur.

I thought of this : 
- Use tabs to switch 2k/2k3/all game
   - https://www.google.com/design/spec/components/tabs.html#tabs-usage
   - Require to find how to know the Rm version of a game x))).

I also thought of displaying a thumbnail, that would be a big UX improvement BUT there are those .LDB parsing and folder's name thing (different depending on version/location). If I find which function are involved in the C++ code I maybe will be able to use them with JNI (after learning how to use it hahaha).

**Comment by Ghabry** [comment] 2015-09-07 16:28
The problem here is that liblcf is not optimized for quickly extracting a single information out of the LDB-database. It always parses all of it, which is a waste of time here. The only feasible approach when using liblcf here is to cache the result... or to write a very simple parser in Java, only extracting title image and version code is simple.

**Comment by Zegeri** [comment] 2015-09-07 20:53
It could create the thumbnail the first time you open the game.

**Comment by fdelapena** [comment] 2015-09-07 21:40
- Fix allow horizontal screen flip preventing activity reset. Having vertical might also be worth, with relative virtual buttons positioning. This is useful for larger screens and buttons are not covering the game screen.
- Joystick custom key mapping support, e.g. for Xperia Play, Ouya and bluetooth pads. I'd prefer this being cross platform but it's OK for now.

**Comment by BlisterBoy** [comment] 2015-09-08 06:47
Haha I was the guy who annoyed you for Xperia Play support, but it's dead snif RIP gaming in train ;'(.
Okay so I'll deeply remake the button mapping system !

Is it a problem if I use JDOM .jar to parse xml ? It use an Apache licence, which is GPL3 compatible.
https://en.wikipedia.org/wiki/JDOM
https://en.wikipedia.org/wiki/Apache_License

**Comment by fdelapena** [comment] 2015-09-08 07:24
According with the license is an Apache-like license but not Apache. Apache 2.0 license is GPLv3 compatible but JDOM license clause 4 is GPL incompatible, according with a related question in debian-legal mailing list.

**Comment by BlisterBoy** [comment] 2015-09-08 07:37
Pff those licences stuff break my balls. Thanks for the explanation !
I'll use a basic format.

**Comment by Ghabry** [comment] 2015-09-08 11:27
Doesn't Java include a XML parser?
Did you consider using json? ;)

**Comment by BlisterBoy** [comment] 2015-09-08 11:32
Oh nice, I didn't even known about that format, thanks Ghabry !

**Comment by Zegeri** [comment] 2015-09-08 13:36
If it used INI, the per-game setting could be loaded/saved from the RPG_RT.ini file. That way, if you want to distribute your game using easyrpg, you could set a recommended default button setting.

**Comment by fdelapena** [comment] 2015-09-08 13:45
+1 for .ini, you can use ini4j and eventually it could be reused later for a non-Android implementation without losing existing stored settings.

**Comment by BlisterBoy** [comment] 2015-09-08 18:32
That's a good idea but the problem is that EasyRPG will have its own button preset list, if the user modifies one, it has to be applied to all game involved. But I can implement a way for a developper to suggest a predefined button mapping in the .ini, EasyRPG would ask the first time to the user if he want to use it.

**Comment by BlisterBoy** [comment] 2015-09-25 15:14
Hi guys.
Some news, I'm working on proportional input layout (between landscape and portrait mode)... And as I thought it's not good. To keep approximatively proportions in portrait I only consider half of the screen. But buttons become too short.
![screenshot_2015-09-25-17-01-30](https://cloud.githubusercontent.com/assets/2387475/10104205/aeb8a8ca-63a8-11e5-9b43-39d7e114f203.png)
![screenshot_2015-09-25-17-01-35](https://cloud.githubusercontent.com/assets/2387475/10104206/aed347e8-63a8-11e5-9313-b82b959f8454.png)



I don't really know what to do, here are some clues : 
- Use fixed sized button in portrait (with adjustment in position, aka the present situation in master branch), and resizable button only in landscape
- Resizable buttons in portrait and landscape mode, but 200% of normal size in portrait

In both configuration there is the risk of buttons on others buttons. But I think the first one is better.

**Comment by BlisterBoy** [comment] 2015-09-25 19:32
- Use resizable buttons in both orientation (based on fixed proportion and not screen resolution), but cheating in portrait with proportion and an horizontal gap seems to be a good choice.

**Comment by fdelapena** [comment] 2015-09-25 19:38
Nice, some users asked for resizable buttons for several devices, they were looking too small. What about another slider to adjust the size by the user if possible?

**Comment by BlisterBoy** [comment] 2015-09-25 19:52
:o 
I was wondering how to display the resizing function for days and you unlocked it in my mind.

Sooooo. 2 options : 
- In ButtonMapping system, display a slider under the last moved button, to resize it in real time (I'll learn one or more thing hihi).
- In Settings Activity, displaying a resize option for every button of every inputLayout (one slider to rule them all)
OR
- Doing the 2 things, BUT with a checkbox in settings, to bypass inputLayout resize configuration (look the best to me).

**Comment by Ghabry** [comment] 2015-09-26 00:04
How about activating a button by touching it (color changes) and then you can resize it by making a zoom gesture (moving two fingers)

**Comment by BlisterBoy** [comment] 2015-09-26 06:50
API 10 my friend :p
But there will be a thing to show that the button is selected and a another to show the possibility to resize it, which is not the case for two fingered movements.

**Comment by BlisterBoy** [comment] 2015-09-27 12:49
Soooo. Here are the Adventures of BlisterB in an Android World™.

To have a clean and an understandable GUI, use discrete sliders is a good idea (better than implement an ugly thing with a textfield actualized in real time).
Good news, Android Visual GuideLine are talking of discrete sliders, they looks awesome : 
https://www.google.com/design/spec/components/sliders.html#sliders-discrete-slider

That's wonderful, this will provide us a wonderful GUI. 
Guess what, those slider doesn't exist.. Nowhere, not in a single API's version.
(That's not a joke XD).

The only solution (like everytime in android) is to use a library that solve the problem: 
https://github.com/AnderWeb/discreteSeekBar 

By chance, this one use a true Apache V2 licence. So we can include it in EasyRPG : 
http://www.apache.org/licenses/GPL-compatibility.html

Does it poses a problem if I use it ?

**Comment by BlisterBoy** [comment] 2015-09-27 13:01
(Of course I can do the textfield thing)

**Comment by Ghabry** [comment] 2015-09-27 23:56
Sure if you think that external libs are useful add them.
What is the problem with your current slider solution? For me it works fine ^^

**Comment by BlisterBoy** [comment] 2015-09-28 08:32
Yep I finally did the other solution and it's not so bad. Sometimes you just go nuts when you see the difference between what they say you can do and what you really can do lol.
I'll remember the libs thing for later, thanks Ghabry !

Btw the Android port really starts to being cool ^^. But the Google Play (in french) highlights just comments talking about past problems.. What a shame ! Is there a way to hide them ? (As they are solved for a long time).

**Comment by BlisterBoy** [comment] 2015-10-01 08:31
Another thing to do : 
Fix the standalone mode.

**Comment by Ghabry** [comment] 2015-10-01 09:43
The standalone mode has one gigantic problem: It wastes twice the space because the game must be extracted out of the assets.
Maybe it should be considered to download the game over the internet on startup instead.
Any other suggestions?

And no we can't hide anything in the Store. Imo it is really stupid, that all rating are weighted the same way. Older ratings should be downweighted to make it possible to get a better rating over time.

**Comment by BlisterBoy** [comment] 2015-10-01 09:59
Yeah that sucks ! Some bad comments from frenchies comes from people which seems to have no idea of what is RPG Maker ^^".

I fixed the standalone mode, I saw the problem of copy folders. Why is there a copy ? Because application cannot write file in asset folder ?  For the moment it's not a big deal, but we can find solution such as copying file in external storage or use a different folder for save/log/etc.
A good thing to implement is the possibility for the maker to indicate preferences (button mapping, screen filter etc.) in a file. It would be loaded in standalone (in game browser mode, a dialog box would ask the first time if the user wants to use the maker's preferences, or user's preferences).

**Comment by Ghabry** [comment] 2015-10-01 10:04
The problem is that the Assets are in in an archive, so you can't get a handle to them from the native code.

This could be worked around by adding extra code to the following FileFinder functions (native code):

```
fopenUTF8 
IsDirectory 
Exists
GetDirectoryMembers
```

Then it should be possible to use the asset dir directly.

**Comment by Ghabry** [comment] 2015-10-04 14:23
The first review already complained, why the new version only occupies half of the screen. :D

**Comment by BlisterBoy** [comment] 2015-10-04 14:25
Wtf are they stupid or something ?  The screen occupy the totality of the screen in one dimension

**Comment by BlisterBoy** [comment] 2015-10-04 14:27
I can only access to french review, does the person complain about the actuel system (which would be stupid) or is it a bug ? Can you copy/past it ?

**Comment by fdelapena** [comment] 2015-10-04 14:45
Add &hl=en or &hl=de or &hl=es from the google play website for other reviews

**Comment by Ghabry** [comment] 2015-10-04 15:01
Of course they are stupid. You can never think as stupid as the worst user :D

```
Why open the game becomes vertical screen, and only half of the screen is displayed on the previous version ....... not so .....

Original review
为什么打开游戏变成竖屏的了，只显示在屏幕上半部分.......以前的版本不是这样的.....
```

**Comment by BlisterBoy** [comment] 2015-10-04 15:10
Thanks @fdelapena !

@Ghabry , is there a way to ask google his location ? I want to piss on his door. Don't tell me he've put a bad rate x). No joking, some comments make me wonder if every user understand they are using a RPG Maker Emulator.

Guys you should look the PR relative to changing directory, I will have less and less time to change it if someone bothers you :/.

**Comment by Ghabry** [comment] 2015-10-04 21:39
He gave 4 Stars.
There are more and more users who ask for an ESC key. But B is the same as ESC... m(

**Comment by carstene1ns** [comment] 2015-10-04 22:13
Time to implement an in-app FAQ. :grinning:

**Comment by fdelapena** [comment] 2015-10-05 00:41
Because some games are documenting "Esc or X" and "B" is unrelated may be confusing, that's why I was suggesting to change it to "X" and then put something in the key mapping like "X (Esc)" and also "Z (Enter)", and show "Z" instead of "A" in the button. I guess most users won't understand the meaning of "B" and "A" and default RPG Maker mappings.

**Comment by BlisterBoy** [comment] 2015-10-05 05:24
@fdelapena , B key in a keyboard really does the same thing than ESC button, as A does the same than Enter

**Comment by BlisterBoy** [comment] 2015-10-05 05:32
I don't know why you proposed X and Y buttons, do you really use those buttons when you use a keyboard ?
Because A and B have the advantage to be a "convention" for everyone since the NES pad. Seriously, just one or two guy don't know this.
If we change theses buttons, more and more people will be confused.

**Comment by Ghabry** [comment] 2015-10-05 08:53
Maybe this could be clarified by changing the text in the "Add button" dialog (the user should see this dialog because he searches ESC).
And changing the text of "B" to: "B (Equal to keys ESC and X)"
(and while doing this "A (Equal to keys ENTER/RETURN and Y)")

**Comment by BlisterBoy** [comment] 2015-10-05 09:09
It sounds to be an excellent compromise

**Comment by Ghabry** [comment] 2016-01-01 13:55
There are 3 minor (?) (well it's Android, maybe they are tricky :D) improvements that would be useful:
[ ] Force Orientation (*) Landscape ( ) Orientation  in settings
[ Edit ] Button in the "Choose Layout" dialog because the users are too stupid to open the settings

In Game:
[ Settings ] to open the settings
[ Edit Layout ] to edit the current used layout

**Comment by BlisterBoy** [comment] 2016-01-01 14:19
>[ ] Force Orientation (*) Landscape ( ) Orientation in settings
>[ Edit ] Button in the "Choose Layout" dialog because the users are too stupid to open the settings

Good ideas, my 2 friends will be available for working on the port in few weeks, this will be a great start for them to understand the project !
Also the Settings Activity start to be quite bulky, dividing option by section will be nice.

>[ Settings ] to open the settings

We can use a "menu" button in game, the app "My Boy!" use this features and I find it usefull.

>[ Edit Layout ] to edit the current used layout

Edit the layout in game would be a good improvement but, Android lolilol => will probably kill the game session while the user edit the layout in another activity x).

**Comment by Ghabry** [comment] 2016-01-01 14:21
I wanted to write the "Force Orientation" on my own. But I gave up after 30min. because I had no idea how to do this. Not even breakpoints worked, the breakpoint is triggered but the activity rotates and native code continues m(

**Comment by BlisterBoy** [comment] 2016-01-01 14:31
Haha don't worry this is their problem now xp.
Screen orientation is a classic exemple of problems with Android : instead of providing a function doing it, we have to overwrite the function onConfigurationChanged(Configuration newConfig) and call it manually  (and praying to not have complains from Samsung's users). This is counter the logic of the architecture, but well...

Even the SettingsActivity itself. Android provide an Activity helping changing preferences, but it's so limited that I was forced to code it like a normal activity x) (this is why the SettingsActivity is so bulky).

**Comment by Ghabry** [comment] 2016-03-14 14:01
Maybe we should consider switching to API14 (4.0.4).

The amount of people running under 2.3.3 is currently less then 2% (200 devices) and the daily install rate of people with 2.3.3 is 1% (~3 devices).

**Comment by BlisterBoy** [comment] 2016-03-14 14:03
How do we do the thumb up icon, I need a lot of them

**Comment by BlisterBoy** [comment] 2016-03-14 14:05
But more seriously, we should try to use the Android Support Library before switching to another API.

**Comment by BlisterBoy** [comment] 2016-03-14 14:18
(But Android Studio propose some really nice and intuitive Activity with API >= 15)

**Comment by Ghabry** [comment] 2016-03-14 14:23
And have to correct myself: API 15 is 4.0.3 :+1:

**Comment by BlisterBoy** [comment] 2016-03-14 14:26
What do you think about keeping the minimum API to 10, but change the target to 15?
Of course, just when somebody will have to implement something using the target 15.

**Comment by Ghabry** [comment] 2016-03-14 14:40
Do what you want. I don't maintain the Android port :dancer:

**Comment by fdelapena** [comment] 2016-03-14 14:58
Interesting article about the API target concept: http://simonvt.net/2012/02/07/what-api-level-should-i-target/

**Comment by Ghabry** [comment] 2016-03-17 09:46
A user suggested an option to disable the music because he prefers listening to his own ;).
Completely disabling is currently possible via "--disable-audio", better control is suggested in #794

**Comment by BlisterBoy** [comment] 2016-03-17 09:49
I was thinking about this and I suggested it to one of the french invaders.
--disable-audio is cool, but it works just at the game launch, right ?

They will try to find a way to modulate the app volume.

**Comment by Ghabry** [comment] 2016-03-17 09:50
I don't want an Android only solution for modulating app volume. This is also useful for other ports (a friend already complained about the loudenss of emscripten)

**Comment by BlisterBoy** [comment] 2016-03-17 10:16
Okay, but the user should be able to modulate the volume in app during a game.

So if I follow you, we should be able from the android app to call a native function (which act as a callback design pattern on the C++ code?) during a game.
If we have such a function, it would be easy to implement the thing from the Android code (a call to changeVolume(value) in onResume( ) and onRestart()).

**Comment by BlisterBoy** [comment] 2016-03-17 10:22
Of course, we could assume that the user has to go in the settings to modify the volume (so stop the game). It makes sense in the actual form of the app, but we won't be able to add a features such as "modify the volume" in the menu of EasyRpgActivityPlayer.
But honestly your solution is fine (it's not a big thing to stop the game), but it would be nice to use a flag with a value, such as --volume 90. To use a spinbar in the settings (I assume some people like me want to hear a podcast, but also have a little volume of the game).

(Of course, we can just have a checkbox to enable/disable volume in Setting, it will be easier to implement - Captain Bash, if your reading that).

**Comment by Ghabry** [comment] 2016-03-17 10:26
See https://github.com/EasyRPG/Player/issues/794#issuecomment-197792437

**Comment by Souigetsu** [comment] 2016-03-17 10:37
- Captain Bash reporting on duty ! 

I'll try adding the volume checkbox :) 

(btw it's kael from the forum, nickname already taken on git )

**Comment by BlisterBoy** [comment] 2016-03-17 10:43
@Souigetsu Thanks Captain, this will be cool waiting the features of Ghabry.

@Ghabry Are you talking of a doing a menu similar to your gamebrowser ?
This will be cool. Maybe a little confusing with the Android GUI but it's not a big thing, we will fing a good compromise when Scene_Options will be ready :).

**Comment by sushi24** [comment] 2016-03-17 11:09
I'll try to help captain on this duty! ;)

**Comment by BlisterBoy** [comment] 2016-03-17 12:06
Don't worry it's pretty simple.
If you have time for another feature, you can do the "Force orientation Auto/Portrait/Landscape", it will be pretty the same as for the Volume features : an option in PreferencesActivity, some condition to add in EasyRpgActivity.

**Comment by Ghabry** [comment] 2016-03-17 12:37
>Edit the layout in game would be a good improvement but, Android lolilol => will 
>probably kill the game session while the user edit the layout in another activity x).

Actually I have this problem with "FB Lite" (FB App replacement): Attaching an image is impossible because it opens an indent e.g. file browser or camera. After selecting an image it returns, the app restarts, because the system doesn't have enough RAM m(

**Comment by Ghabry** [comment] 2016-04-12 17:50
@BlisterBoy  another useful feature would be a language select in the settings. If somebody hates our translation ;)

**Comment by Ghabry** [comment] 2016-10-04 15:59
@BlisterB  can we close this meta-issue?

**Comment by BlisterB** [comment] 2016-10-04 16:18
Of course :)

**Closed** 2016-10-04 16:40 UTC
Labels: Android
