### ISSUE TITLE
Bug "Random Movement" with Frequency "nX"

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#2436] opened 2021-01-10 10:15 UTC
**Name of the game**: Super Crystal Hunter (2k3 steam) - Minigame "Grenade Sheep"

**Player platform**: Windows x64

**Attach files (as a .zip archive or link them)**
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/5792400/easyrpg_log.txt)
https://user-images.githubusercontent.com/1331889/104124145-56e06380-534f-11eb-9a96-49674fb43e58.mp4

Normal behavior: https://youtu.be/a-puNA6NO1Y

Config of the wolves:
![imagen](https://user-images.githubusercontent.com/18174790/104120141-c9901580-5334-11eb-9e4c-00647114a8d3.png)

**Describe the issue in detail and how to reproduce it**:

There is nothing special about the mini-game, simply when the wolves fall (spritesheet) you place the events of each wolf with the settings of the previous screenshot.

When the wolves die, another spritesheet is processed. But what the random movement of the wolves is is no mystery.

For some strange reason the wolves get stuck on the leftmost tiles and only move up and down

Thanks guys.

**Comment by Ghabry** [comment] 2021-01-10 13:23
Github allows embedding of videos now, did that for your video.

**Comment by Br4ssman** [comment] 2021-01-10 13:46
Thanks @Ghabry I didn't knew that ^^'
btw, I want to note that the wolves have his graphic as "Direction Fix/Inanimated", because that can be related with the bug, maybe.

**Comment by rueter37** [comment] 2021-01-30 09:46
@Br4ssman you are right with your assumption that the graphic animation setting set to "Direction Fix/Inanimated" is the culprit. I can reproduce the bug this way. As soon the face direction is locked, the random movement behavior for some reason doesn't allow moving towards the direction the event is facing. This explains why the wolves are never moving to the right, because they are facing right and have the face direction locked. Moreover this bug occurs independent of the move frequency.

**Closed** 2021-01-31 17:39 UTC
Labels: Event/Interpreter, Patch available, Regression
