### ISSUE TITLE
Stuck event (unterwegs in düsterburg)

### ISSUE THREAD

**Issue by Hoozuki** [EasyRPG/Player#668] opened 2015-12-09 10:05 UTC
Hi,

I found another event that stops game progress, very similar to the bug in grandy's house that was fixed a couple of days ago.

In the house of the occult expert in Königsberg, an event occurs as you are brought upstairs into your room, when the owner of the house encounters malthur for the first time. They have a short conversation and as soon as the expert tries to leave the room, the event is stuck. 

I will provide a savegame just in front of the mentioned house.
The following steps are necessary to get to said event:

-Knock on the door
-In the dialogue, choose "Freunden von Dankwart"
-Enter the house and go straight into the room with the 3 guests
-Talk to any 2 of them
-Leave the room and talk to one of the two clerks and follow them upstairs
-Inside the room, the cutscene occurs.

Thanks for your efforts! :)

Here is the attached save file:
[Save10.zip](https://github.com/EasyRPG/Player/files/56608/Save10.zip)

**Comment by Zegeri** [comment] 2015-12-11 21:44
Thank you, this is a duplicate of #665. Patch: 96cc9bc.

**Comment by Ghabry** [comment] 2015-12-11 21:48
Closed as a duplicate. Please see #665 for further discussion on this issue (A fix is already prepared and will come during the next days)

**Closed** 2015-12-11 21:47 UTC
Labels: Duplicate, Events, Hang, Interpreter
