### ISSUE TITLE
Timer and parallel processes issue

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#1165] opened 2017-05-16 17:00 UTC
#### Attach files (as a .zip archive or link them)
[easyrpg_log.txt](https://github.com/EasyRPG/Player/files/1005239/easyrpg_log.txt)
[TestEasyRPG.zip](https://github.com/EasyRPG/Player/files/1005243/TestEasyRPG.zip)
[Video Issue.zip](https://github.com/EasyRPG/Player/files/1005247/Video.Issue.zip)

#### Describe the issue in detail and how to reproduce it: 
Hi, to help you detect the issue, the main coder of our game created a small RPGM2K3 project containing only the code and the resources needed to test the problem. If he plays this "game" on RPGMaker (on its PC), when the timer elapses, the animated finger disappears from the screen, no more "pressing" sound and he sees only a relaxing black screen (while in our full game the action goes on). If he plays it on EasyRPG (on its Galaxy S7), when the timer elapses the finger remains on the black screen forever, still animated and still making noise. Our main coder's guess is that, for some reason he dosn't know, the two parallel processes which control the animation/sound of the finger and the response to the user's key press, in order to fill the bar, in EasyRPG are not deactivated when the timer elapses. Both parallel processes are actived by the "Switch 0975: timer special" and when this switch goes OFF, they should stop processing. This doesn't seem to happen in EasyRPG.
Let us know and thank you.

**Comment by Ghabry** [comment] 2017-05-16 18:26
The problem is that the code checks for "Timer >= 1s" and afterwards "Timer <= 0s". And when both cases are false the event is deleted.

Both false didn't happen in RPG_RT but for EasyRPG this was the case because the timer decrements and will be in the interval from 0.01s and 0.99s. But RPG_RT actually rounds this up to 1s..., so the 1st check is true until the timer is really 0.00s.

**Comment by zell180** [comment] 2017-05-16 19:00
How can we fix this with little effort?

**Comment by fdelapena** [comment] 2017-05-16 19:23
A fix has been committed for this bug, if you want to test it, you can try the following test builds:
- [Windows build](https://ci.easyrpg.org/job/player-win32-pr/1313/artifact/bin/easyrpg_windows.zip)
- [Android build](https://ci.easyrpg.org/job/player-android-pr/1063/artifact/builds/android/app/build/outputs/apk/EasyRpgPlayerActivity.apk)

**Comment by zell180** [comment] 2017-05-16 20:56
Our coder changed the code of our game and then it worked in RPGMaker and in EasyRPG too. By the way, I used your Android test build with the old version of our code (the one that didn't work in EasyRPG only) and it worked fine. We prefer not to change all the points in our game where we do use timers. Therefore: can you confirm me that this fix for the timer will be part of the next official build of EasyRPG?

**Comment by Ghabry** [comment] 2017-05-16 21:44
Yes. Because thats a bug in Easyrpg it wiĺl be fixed in the next release

**Comment by zell180** [comment] 2017-05-16 21:44
Thanks!

**Closed** 2017-05-21 21:50 UTC
Labels: Event/Interpreter, Patch available, Testcase available
