### ISSUE TITLE
のび太のバイオハザード/のび太のバイオハザード2のバグについて

### ISSUE THREAD

**Issue by turna-omega** [EasyRPG/Player#692] opened 2015-12-23 07:44 UTC
のび太のバイオハザード
エンブレム/ゴールドエンブレムをはめると、エンブレム/ゴールドエンブレムが設置されずに無くなる

のび太のバイオハザード2
会議室前の廊下の脚立に登れない

**Comment by fdelapena** [comment] 2015-12-27 16:12
@turna-omega 問題のレポートをありがとうございました。

I've confirmed the first bug report in Nobita's Resident Evil 1. It looks like this bug might block the game continuation:

There is a school badge object called "Emblem" in the inventory which can be used to put it on a placeholder.
The object has some event triggering when not used in the right place, showing a hint about where to use it. When it can be used (in the right place/tile at the second floor north wing), it should trigger something more, however the objects gets used (disappears from the inventory) and the placeholder remains as before.

[Savegame download](https://fran.cr/owncloud/index.php/s/1JPKv08AftCx2lV/download). To verify, just leave the computer room (there is an RPG Maker or game bug when loading the saved game with an invisible closed door there (should it be opened or visible?), probably not a Player bug), leave the map and go in the corridor to the left and you will find the following hole to use the emblem object from the inventory:

![School badge emblem placeholder](https://cloud.githubusercontent.com/assets/174885/12010930/5626fc9a-ac80-11e5-8655-b10717c40cbc.png)

**Comment by fdelapena** [comment] 2016-01-14 00:45
The problem with のび太のバイオハザード2 seems to be the same bug as #714, according to the warning displayed.

Link to download のび太のバイオハザード2 available at: http://www42.atwiki.jp/nobitahazard-wiki/pages/228.html
This game has not been translated to English yet.

It is a .zip with SHIFT_JIS filenames. To unpack:

    unar nobihaza2.zip

![Stairs](https://cloud.githubusercontent.com/assets/174885/12312392/b4a358de-ba24-11e5-8262-735fa97b656b.png)

By the way, this game seems to have serious issues with some zombie movements. Also, gun firing seems to fail when the enemy is more than 1 tile away. This is working properly in nobihaza1.

**Comment by fdelapena** [comment] 2016-01-25 18:16
> のび太のバイオハザード2
> 会議室前の廊下の脚立に登れない

@turna-omega this issue [has been fixed](https://github.com/EasyRPG/Player/pull/736) and will be included in the next EasyRPG Player release.
![Fixed](https://cloud.githubusercontent.com/assets/174885/12559791/a778f40c-c35c-11e5-9cd8-6a04ffc8ceaf.png)

**Comment by scurest** [comment] 2016-01-26 06:10
その場しのぎだけが、窪みの前でまずは文書のアイテムを使って動かずエンブレムを使ったら、設置できます。

**Comment by fdelapena** [comment] 2016-01-26 13:40
Thanks @scurest for the hint. Then this issue seems related with parallel event interaction issues. 
I've tested with @Zegeri's [Player development branch](https://github.com/Zegeri/Player/tree/development) and this issue is working properly.

**Closed** 2016-02-08 23:18 UTC
Labels: Events, Interpreter, Patch available

**Comment by fdelapena** [comment] 2016-02-08 23:38
> のび太のバイオハザード
> エンブレム/ゴールドエンブレムをはめると、エンブレム/ゴールドエンブレムが設置されずに無くなる

@turna-omega this issue [has been fixed](https://github.com/EasyRPG/Player/pull/753) and will be included in the next EasyRPG Player release.

![Fixed](https://cloud.githubusercontent.com/assets/174885/12903084/9e7b0ef6-ce8a-11e5-8b47-0245d9f1ab65.png)
