### ISSUE TITLE
Damage Calculation again

### ISSUE THREAD

**Issue by lyehborealis** [EasyRPG/Player#844] opened 2016-03-23 12:17 UTC
Collective Magic attacks only hits one enemy not all the enemies.
Frequently magic attacks only do 1 damage. 
Thanks.

**Comment by Ghabry** [comment] 2016-03-23 12:56
Could we have a test case?

Name of the game +
a savegame next to a battle where this can be reproduced +
Which skills fail

**Comment by Tondorian** [comment] 2016-03-31 23:46
At least in Maker 2k games all enemys get damage 
Scope_enemies is usaged twice in `scene_battle.cpp` (l. 342, 450) so it should also work in rpg2k3 correctly.
I think all this strange behavior results, because my old condition/Attribute code ignores attacks when there was no attribute on weapon/skill.
So it should be fixed now

**Comment by Ghabry** [comment] 2016-04-15 20:21
This was probably one of the 0.4.1 regressions and we never got feedback...

**Closed by Ghabry** 2016-04-15 20:21 UTC
Labels: Battle, Invalid
