### ISSUE TITLE
Mother: Cognitive Dissonance - Issue Documentation

### ISSUE THREAD

**Issue by ChrisHighwind** [EasyRPG/Player#1414] opened 2018-09-06 17:54 UTC
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
Mother: Cognitive Dissonance

#### Player platform:
Mainly tested on Vita, though may apply to other platforms

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)
[MCD.zip](https://github.com/EasyRPG/Player/files/2358163/MCD.zip) (Savegame and log.txt are both contained in the zip)

#### Describe the issue in detail and how to reproduce it:
These issues are mainly minor, and do not affect gameplay heavily, but I'm not sure if they can be rectified within the goals for EasyRPG:

- [x] PP and ATB bar overlap each other (though both are still readable and can be made out with a little effort) **since 0.6**
- [ ] (Battle windows in general default to normal in the Player instead of use the custom layout the game has)
- [x] Enemies and Battle Backgrounds aren’t animated (Battle Backgrounds are supposed to resemble those found in the SNES RPG Earthbound, with animated effects depending on the enemy group being fought, plus some enemies in this game have simple animations as well) **since 0.6**
- [x] When dual-wielding pistol weapons, Col. Saturn only attacks once (When Col. Saturn is equipped with two weapons, he is supposed to attack twice upon selecting the "Shoot" command) **since 0.6**
- [ ] Enemy Encounter sound doesn’t stop upon entering the battle transition, and as such plays over the battle music for a brief moment at the start.
- ~~Dr. Saturns do not heal status effects, but hotels and similar do. (Dr. Saturns, i.e. the Mr. Saturns in trash cans, are supposed to heal status effects without recovering HP and PP, and hotels and other places where the protagonists can sleep are supposed to recover HP and PP, but retain status effects)~~

**Comment by Ghabry** [comment] 2018-09-06 18:31
Where can we find the version of CogDis you used? I installed this one http://cogdis.tazmily.com/ but some monster names and events don't match with your logfile.

Is the trashcan & sleeping close to the save game location?

**Comment by ChrisHighwind** [comment] 2018-09-06 18:38
I used the "Magicant Edition" of CogDis, which can be found in the official Discord as a pinned message in the #announcements channel. I'm not sure if I'm allowed to link it here, as it is a dev build that is generally not intended for public release, but has some improvements over the version on the main site.

**Comment by Ghabry** [comment] 2018-09-06 20:14
The "Debug: Common Event 27: Erasing of the calling map event only supported in RPG2k3E" logs (happens in multiple events) are suspicious because there is no Erase Event used.

**Comment by carstene1ns** [comment] 2018-12-13 21:31
At least dual weapons have been fixed already.

**Comment by Ghabry** [comment] 2019-02-10 21:48
#1605 fixes "PP and ATB bar overlap each other" but the layout is still partially wrong and Enemies and Battle Backgrounds aren’t animated

**Comment by Ghabry** [comment] 2019-02-10 21:57
> Dr. Saturns do not heal status effects, but hotels and similar do

This is incorrect. According to the event script they only heal KO state and give a +9999 HP after removing KO.

**Comment by ChrisHighwind** [comment] 2020-06-29 14:11
A very tiny detail I've noticed about the latest builds and the game's original exe regarding the multiple attacks is that in the original exe, each attack plays the attack animation, so in the case of, say, the Borange Ray, which does 2 attacks with every one ray equipped, the attack animation plays, the enemy takes damage, and then repeat, or if Col. Saturn is dual-wielding weapons, then the attacks happen one after the other instead of all at once which I assume is the case currently.

Also, another thing I've noticed is that some music, notably the Fourside theme when in your home base on Saturn in Chapter 3 and beyond, tends to sound choppy and slow in EasyRPG

**Comment by TheNamesGregoryAndounuts** [comment] 2020-12-06 10:08
Don't forget my issues!

**Comment by rueter37** [comment] 2021-03-17 18:24
I cannot reproduce the remaining bugs on current master. Maybe they are already fixed?

**Comment by fdelapena** [comment] 2021-03-20 20:34
I'm also unable to reproduce them, dual wield was also fixed in previous PRs.
Marking as closed, please reopen if issues persist.
Regarding audio issues, if the music is MIDI based, there have been recent fixes on wildmidi. Anyways it's going to be replaced with a different synthesizer soon.

**Closed by fdelapena** 2021-03-20 20:34 UTC
Labels: Battle, Event/Interpreter
