### ISSUE TITLE
LcfTrans translations back into the game from external file.

### ISSUE THREAD

**Issue by rygos** [EasyRPG/Player#1211] opened 2017-06-28 13:12 UTC
With LcfTrans strings can be extracted from the game files.
It would be nice if these strings can be loaded with external (!) Language files with the player. 
Just think about community translations =)

The initial idea came from Ghabry.

**Comment by fdelapena** [comment] 2019-03-05 20:12
Not sure if a dupe of #797, but I vote for this approach with [tinygettext](https://github.com/tinygettext/tinygettext) from liblcf :+1:.

**Comment by fdelapena** [comment] 2021-02-23 19:33
Note this is not the same as updating the game files, which is different and unlikely to get implemented because loading from PO files provides the same functionality in practice.

This is already implemented in #797. For a rough guide check this [community lcftrans translation guide](https://community.easyrpg.org/t/support-for-accented-letters/913/4).

**Closed by fdelapena** 2021-02-23 19:33 UTC
Labels: Duplicate, Enhancement, Feature Request
