### ISSUE TITLE
Aëdemphia: game controls stop working and shows callstack depth exceeded

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#2014] opened 2019-12-25 23:07 UTC
#### Player platform:
Android, at least (reported via email Bug Report app feature).

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game) [issue-2014.zip](https://github.com/EasyRPG/Player/files/4000872/issue-2014.zip)
 - The `easyrpg_log.txt` log file (you can find it in the game directory) [easyrpg_log.txt](https://github.com/EasyRPG/Player/files/4000873/easyrpg_log.txt)

#### Describe the issue in detail and how to reproduce it:
Reported via email by Damien (translated from French):
> A message appears at the top of the screen and the controls no longer work. But the game continues to turn. It obliges to relaunch the app.

The messages shown at the top, according to easyrpg_log.txt are the following:

    Warning: Interpreter: Maximum callstack depth (100) exceeded [6x]

Note this game uses patches, so they may affect on this behavior. Added the RPG_RT Patches label just in case until it is confirmed is unrelated.

**Comment by fmatthew5876** [comment] 2020-01-05 01:55
This is likely fixed in master.

Our current call stack depth limit is 1000.

**Comment by Ghabry** [comment] 2020-01-10 20:48
How can you even reach a callstack depth of >100 in RPG 2000 wtf, this game has the worst of everything.

**Comment by Ghabry** [comment] 2020-03-31 23:02
Cannot reproduce.
Tested 0.6.1 and master.

**Closed by Ghabry** 2020-03-31 23:02 UTC
Labels: Event/Interpreter, Hang, Needs feedback, Patch available
