### ISSUE TITLE
Blue flash bug 3ds easy rpg in every game

### ISSUE THREAD

**Issue by MCkringle** [EasyRPG/Player#3011] opened 2023-05-19 22:30 UTC
#### Player platform:
N3dsxl, and 2ds

#### Attach files (as a .zip archive or link them)
 - A save [game]([easyrpg_log.txt](https://github.com/EasyRPG/Player/files/11520878/easyrpg_log.txt)) next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Every 2000 and 2003 rpgmaker game on both a new 3ds and 2ds, cause the screen to flash blue briefly when opening a menu or switching rooms in game, and while it doesn't really break anything or cause bugs (that i am aware of) it's very immersion breaking and I was wondering it's an easy fix at all, or if it's just a product of something like the ram being only able to handle one screen at a time and it loading it a new scene causes it. 
Whatever it is, the problem isn't present on the switch with those games, and yeah I'm using the 0.8 release on both 
any help is highly appreciated, as the games seem entirely stable outside of this

**Comment by Mimigris** [comment] 2023-05-19 22:33
This issue is a duplicate of #2981 . If possible there will be an attempt to fix it for the upcoming bugfix version.

**Comment by Ghabry** [comment] 2023-05-21 19:22
Thanks. I will close this as is an exact duplicate of the issue linked by Carbonara.

I will try to get this fixed soon as is obviously very annoying.

**Closed by Ghabry** 2023-05-21 19:22 UTC
Labels: Duplicate
