### ISSUE TITLE
Controller issue in EasyRPG Libretro core - Ara Fell

### ISSUE THREAD

**Issue by fry-guy** [EasyRPG/Player#2531] opened 2021-05-14 16:41 UTC
Hi. There appears to be a controller bug in EasyRPG libretro core version 0.6.2.3... In Ara Fell (full version, Steam), the arrow keys no longer work on the main menu and also the Y key ("shift") no longer works. This means the game isn't playable since you can't navigate the maps without the ability to crouch. You also can't even load your save games unless you hit "A" immediately after the developer splash screen, which jumps you straight to the "continue" option, as otherwise that option is unselectable due to the arrow key issue.

I encountered this error in RetroArch version 1.9.2 running on 351Elec, a custom firmware for a handheld Linux-based device. I reported the issue on their page and they encouraged me to report it "upstream." https://github.com/351ELEC/351ELEC/issues/386

Notably, I did not encounter this error in version 0.6.2. Also, the problem seems very similar to this issue described here - EasyRPG/Player#787 - which was supposedly resolved a few years ago? This post also suggests there may be some issue in RPGMaker called the "stuck key glitch"? https://steamcdn-a.akamaihd.net/steam/apps/440540/manuals/AraFellREADME.pdf?t=1461965438

If this is not the proper place for reports related to the libretro core, please let me know. I'm also happy to provide any more details on this error, if requested.

Thank you for looking into this, and for your work on this great software!

**Comment by Ghabry** [comment] 2021-05-14 16:45
Hello. Can you try this with a continuous build from our website and check if the bug is still there?
Note there are no cores available. Only "normal" binaries.

https://easyrpg.org/player/downloads/#snapshot-windows

**Comment by dj5927** [comment] 2021-05-25 07:59
I am in a similar situation.

Zelda awakening the arrow keys do not work in some situations.
With the opening
Arrow keys are not recognized in the Enter Name and Set Items window.

Also, there is a problem with the expression of motion animation.

You can go somewhere else normally.

retroarch 1.9.3
0.6.2.3 core is in use.

In 0.6.1 there was no problem.

**Comment by fry-guy** [comment] 2021-09-11 05:44
Hey, so I left off of this for a really long time, but I finally downloaded a copy from your website today and tried it and am still encountering the same problem. I used the Windows 64-bit version. Still no shift key control. Also - not sure if this is related - but also discovered the f5 key doesn't work - that's supposed to bring up the game settings. That also doesn't work but in the libretro core and the Windows version.

Regarding the "continuous build" on your website, I didn't see any libretro core on there. The site directed me to the buildbot site. But, again, I also tried the Windows version and got all the same errors.

Thanks again for looking into this. Sorry I took so long to answer you!

**Comment by fry-guy** [comment] 2021-09-11 14:29
No idea if this is related but here’s another game that appears to have a similar issue with the shift key: https://github.com/EasyRPG/Player/issues/997

**Comment by Ghabry** [comment] 2021-09-11 14:36
@fry-guy  I have Ara Fell on Steam but no idea how to get the legacy version that still uses RPG Maker 2003 :/. Any idea how to get it?

And could you attach a "easyrpg_log.txt"? It should be in the game directory.

**Comment by Ghabry** [comment] 2021-09-11 14:58
found it, needs Compatibility option "Windows" set in steam because the Linux download does not have it .........

**Comment by Ghabry** [comment] 2021-09-11 15:13
The problem is that we forgot to set the ``EngineMajorUpdated`` flag when English 2003 version is detected. upps. Only the "English flag" was set.

The "not setting Major flag" bug is 5 years old: https://github.com/EasyRPG/Player/commit/f802fa365ff5daa5a8d7ba41c807102a952b0e8a

but there are only two cases where Updated changes the behaviour:
- Handling of Arrow Keys and Shift in KeyInputProc, since https://github.com/EasyRPG/Player/commit/a7118b1a9985f6618791b5a2d4c85b2c0d453763
- The Layer feature and Animations are Above pictures, since https://github.com/EasyRPG/Player/commit/39def62279958e96e0367c027360502aad658a0d

So yeah 2 features are broken here since at least 16 months. :(

**Comment by fry-guy** [comment] 2021-09-11 15:27
Glad you understand what's causing the issue - cause a lot of this is Greek to me... Will you able to fix it in a future update then by fixing that flag? Or is the bug you mention one that hasn't been solved yet?

**Comment by Ghabry** [comment] 2021-09-11 15:29
It will be fixed in the next release

**Closed** 2021-09-11 16:26 UTC
Labels: Regression, Pictures

**Comment by fry-guy** [comment] 2021-09-18 21:34
> It will be fixed in the next release

Do you know when this will be, approx? Is there a way to get notified? Thanks again!

**Comment by fry-guy** [comment] 2021-09-18 21:35
> It will be fixed in the next release

What's the best way to get notified of the next release? Thank you.

**Comment by fdelapena** [comment] 2021-09-19 01:19
> What's the best way to get notified of the next release? Thank you.

Formal announcements are done from the [EasyRPG blog](https://blog.easyrpg.org/), you can use a feed reader to subscribe to rss/atom to track new blog updates. [EasyRPG on twitter](https://twitter.com/easyrpg) is another way to get announcements.

For package maintainers, you can subscribe to atom feeds from GitHub, for example, for Player: [releases](https://github.com/EasyRPG/Player/releases.atom), [tags](https://github.com/EasyRPG/Player/tags.atom). Or from the [Anitya](https://release-monitoring.org/) service.

**Comment by fry-guy** [comment] 2022-02-17 21:47
This release (Sword 0.7.0) still does not appear to be available for use on retropie. Will it ever be updated in buildbot? https://buildbot.libretro.com/nightly/linux/armhf/latest/ Is there a way that I can compile myself? Thank you. @fdelapena @Ghabry

**Comment by fry-guy** [comment] 2022-03-20 16:14
For anyone who stumbles across this post, I was able to successfully install the libretro core of easyrpg version 0.7.0 on retropie with this script: https://github.com/mictjs/RetroPie-Extra-WIP/blob/master/scriptmodules/libretrocores/lr-easyrpg.sh
