### ISSUE TITLE
So many bugs of "Surprisia" 

### ISSUE THREAD

**Issue by dlwlgp653** [EasyRPG/Player#711] opened 2016-01-07 12:48 UTC
Game introduce and download : http://acoc.kr/index.php?mid=votedgame&category=718315&document_srl=853700

First Bugs, an overlap of character during battle.
Second, be changed to zero percent skill
Third, given Damages or combat that it does not reduce the value when it consumes ap
Fourth, they are not the death of character
Fifthly, the incorrect message is printed on the combat situation 
Ex) can lid open, but nothing's happening, a cat. (고양이 캔 뚜껑을 열어보았지만 아무 일도 일어나지 않았다.)
A lot of games due to bug going on is unpleasantly hard. 
test, please.

**Comment by dlwlgp653** [comment] 2016-01-07 12:53
이 게임은 한국의 한명이 5년 6개월동안 제작해 완성한 게임이며, 지금까지 패치를 거듭하고 있을정도로 애착이 대단한 게임입니다. 스마트폰으로 엔딩을 보는게 제 새해 소원중 하나이므로 테스트 하셔서 꼭 버그 수정을 해주셨으면 합니다.

**Comment by fdelapena** [comment] 2016-01-07 14:56
Thank you @dlwlgp653

For developers: the download link is the link with the "[다운로드]" text.

To unpack:

    unar SurprisiaCompletev1.13d.zip
    cd SurprisiaCompletev1.13d
    unar --encoding EUC-KR 서프라이시아.lzh

There are some issues when unpacking some files (some maps), maybe the lzh file is somewhat corrupted, but the game still works.

How to reproduce some bugs:

> First Bugs, an overlap of character during battle.

- `--battle-test` will reproduce the character overlap (automatic placement of battlers issue? #278)

![Character overlap](https://cloud.githubusercontent.com/assets/174885/12173256/5e11aa1a-b51b-11e5-802a-09f3b63f751f.png)

> Fifthly, the incorrect message is printed on the combat situation 

- Something is wrong with the battle event interpreter (is somewhat related with #488?)

![captura de pantalla de 2016-01-07 08-36-13](https://cloud.githubusercontent.com/assets/174885/12173374/13d3f0e2-b51c-11e5-85af-ace28bb21060.png)

To reproduce this issue, you need to play from the game itself. Just leave the main town map going to the south and map battles will start soon in the next map. It can't be reproduced with the current `--battle-test` database configuration.

**Comment by dlwlgp653** [comment] 2016-01-07 17:20
If you modify the number of bugs in the game there are going to donate money to you . 
It means am so has a lot of passion for the game I hope to come modification.
When I confirmed that the game would normally be driven to reciprocate by sending you a dollar via PayPal .
So please do your best to fix bugs .

**Comment by fdelapena** [comment] 2016-02-18 03:43
> Second, be changed to zero percent skill
> Third, given Damages or combat that it does not reduce the value when it consumes ap
> Fourth, they are not the death of character

@dlwlgp653 could you try again these issues with this version? Download: [Android APK](https://easy-rpg.org/jenkins/view/Pull%20Requests/job/player-android-pr/lastSuccessfulBuild/artifact/builds/android/bin/EasyRpgPlayerActivity.apk), [Windows](https://easy-rpg.org/jenkins/view/Pull%20Requests/job/player-win32-pr/lastSuccessfulBuild/artifact/bin/easyrpg_windows.zip).

**Comment by dlwlgp653** [comment] 2016-02-18 10:27
Wowwww, I waited for you Thank you very much! i will test.

**Comment by carstene1ns** [comment] 2016-03-29 00:01
I have opened a dedicated issue for the battler placement: #851, as it affects also other games.

**Comment by Ghabry** [comment] 2016-04-15 20:19
Closing this one because battle placement is resolved and battle interpreter issues are tracked in #488 and #788 
And the damage calculation complains should be also fixed.

**Closed by Ghabry** 2016-04-15 20:19 UTC
Labels: Battle, Duplicate
