### ISSUE TITLE
Games with altered file extensions

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1920] opened 2019-10-06 13:06 UTC
A few games, e.g. Laxius Power use modified file extensions.

Player will fail to detect such games because RPG_RT.ldb is missing.
No idea how to support this.

File extension changes:
Rpg_rt.ldb to Rpg_rt.set
Rpg_rt.lmt to Rpg_rt.lxb
and all the MapXXXX.lmu to MapXXXX.ont

**Comment by sorlok** [comment] 2019-11-05 03:34
So I'd like to try fixing this. There's basically 3 things that need to be done:

1) Detect that a folder *might* have renamed game files.
2) Figure out which files were renamed.
3) Fix any internal string renames (things like "LcfMapUnit" are sometimes mangled on purpose).

Note that for all 3 steps, I'd like to avoid reading bytes from RPG_RT.exe directly if possible.

(1) is easy: count the number of "RPG_RT.*" files (should be 3) and "MapXXXX.*" files (should be >0).

For (2), we can assume from (1) what the Map extension is. Of the 3 RPG_RT.* files, 1 is ".ini", and the *larger* of the remaining 2 is almost certainly the database. We could also try parsing the guessed "LMT" file and seeing if it passes, but this seems like overkill. Finally, I'd like to add an option to read the custom extensions from metadata (since we have the RPG_RT.* checksums).

For (3), I think we'll need to just disable the "LcfXXX" checks inside the liblcf parser whenever a custom file extension is in use. Alternatively, if we used metadata for (2), we can also retrieve the "LcfXXX" replacements from metadata, which is a little more reliable.

This approach should support custom extensions with minimal fuss. Let me know if this seems like a good approach and I'll start on a prototype.

**Comment by Ghabry** [comment] 2019-11-05 08:55
Thanks for working on this :)

This issue can be split in two categories:

Main issue:
 - [ ] Support loading of "folders" with altered file extensions

Secondary issues:
 - [ ] Support in game browser (Game with renamed files listed)
 - [ ] Support in Android Game Browser. See https://github.com/EasyRPG/Player/blob/master/builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserHelper.java#L45

I would consider this resolved (and open a new issue) when the *Main issue* is fixed but you can decide if you want to fix all of them.

-----------------------------------

> (1) is easy: count the number of "RPG_RT." files (should be 3) and "MapXXXX." files (should be >0).

Better check for 2 as some games have no .ini file.

> For (2), we can assume from (1) what the Map extension is. Of the 3 RPG_RT.* files, 1 is ".ini", and the larger of the remaining 2 is almost certainly the database. 

Okay lets assume for now that huge = LDB, smaller = LMT, smallest = INI.
Good thing is: This heuristic will be only needed when the extensions are altered, so the false positive rate should be very low. (and when the heuristic fails we can expect a bug report).

> For (3), I think we'll need to just disable the "LcfXXX" checks inside the liblcf parser

These checks are already skipped. The parser only checks the string length (there is a huge amount of games with hex edited headers).

**Comment by sorlok** [comment] 2020-07-23 06:20
Good evening,

PR #2271 has my first draft at a fix for this. Apologies for dropping off the face of the earth; I broke some bones in an accident and was unable to do computer work for a while. 

It's been a while since I started this, so please let me know any feedback for my fix (and then I will rebase it). Tested with Laxius Power, Battle for Genesis, and a private project that renames LMU files.

Thanks!

**Comment by sorlok** [comment] 2020-07-24 01:25
As of the latest commits, I've confirmed PR #2271  fixes all 3 issues identified above (loading from a directory, using the game browser, and using the game browser on Android).

I'd still like some feedback, since my programming's a bit rusty. (Also, my email claims there was a comment on regexes, but it seems to have disappeared.)

**Comment by sorlok** [comment] 2020-07-26 17:37
I've made additional fixes as suggested, and rebased+squashed PR #2271 . I think I'm done with things on my side.

For those wishing to scan their own project folders for non-standard games, the following script should prove useful:
https://drive.google.com/file/d/1iv2YHQ_DFXRWgixeojaWUbgxZkzJ7ODl/view?usp=sharing

**Closed** 2020-09-02 10:01 UTC
Labels: FileFinder, Patch available, RPG_RT Patches
