### ISSUE TITLE
Charset disappear after talk

### ISSUE THREAD

**Issue by zell180** [EasyRPG/Player#2196] opened 2020-05-04 14:34 UTC
#### Name of the game:
Saint Seiya -Il Mito-

#### Player platform:
Android

#### Attach files (as a .zip archive or link them)
[Save01.zip](https://github.com/EasyRPG/Player/files/4575272/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
After talk with NPC she disappear. Select "No, ho troppo sonno adesso" to short talk

**Comment by Ghabry** [comment] 2020-05-04 14:40
This is slowly becoming too much work for me:

1. Can I share the game you provided to me with other devs?
2. If not: Please create a minimal testcase to reproduce this

**Comment by zell180** [comment] 2020-05-04 17:17
Solved. Error in our code.

**Comment by zell180** [comment] 2020-05-04 17:47
I've shared the game. Issue persist, if you use save not happens.

**Comment by fmatthew5876** [comment] 2020-05-14 04:48
I can reproduce this with the second save zell180 uploaded.

This one has something to do with something in the save game. If you edit and save the map, the bug no longer happens. If you then comment out the `save_count` code, the bug occurs again.

It happens immediately after Event 349 / page 3 finishes executing.

**Comment by zell180** [comment] 2020-05-14 05:59
I think this information can help you: the bug occurs even if you get to that part of the game without loading the save

**Comment by fmatthew5876** [comment] 2020-05-16 01:46
This happens right when the event finishes executing. I added a message at the end of the event to verify.

1. Turns on switch for page 4
2. Refresh runs, setting up new page
3. Message appears
4. Message closes
5. sprite dissapears

If you edit the game map, you have to disable the `save_count` logic in `Game_Map`, otherwise the bug will not happen.

**Comment by fmatthew5876** [comment] 2020-05-16 02:22
Also checked with ubsan and address sanitizer. Nothing on this bug

**Comment by fmatthew5876** [comment] 2020-05-16 03:02
Ok I've figured this out.

The save game has `direction=4` (UpRight) and `sprite_direction=1` (right)

When you talk to the event, her `sprite_direction` changes to face you. Once the event finishes, Player will do `sprite_direction = direction`.

After that the sprite rendering code computes a bounding rect with `sprite_direction == 4` which ends up out of bounds. So you get a `Sprite::src_rect` with `height == 0` and this is what causes the event to dissapear.

This also explains why the bug doesn't occur when `save_count` logic triggers, because all the events get reset. Her direction must have changed to 4 from a previous event and saved into the save game.

Resetting the events `sprite_direction` after the event finishes is correct, but we do it wrong. First, in RPG_RT `sprite_direction` or `facing` as they call it can never be a diagonal direction.

RPG_RT actually has a virtual function in the `Character` class heirarchy which resets facing based on current direction.

To reproduce this bug is simple.  Make an event with custom move route `Move UpRight, no repeat`. Put some message in, Then talk to it. The event will disspear after the message.


This will be fixed in #2208 , but it is not yet.

**Comment by fmatthew5876** [comment] 2020-05-19 01:25
This is now fixed in #2208

**Closed** 2020-09-21 05:59 UTC
Labels: Move Routes, Patch available
