### ISSUE TITLE
“No viable conversion from 'std::ifstream' to 'const std::string'”

### ISSUE THREAD

**Issue by bentley** [EasyRPG/Player#1305] opened 2017-11-02 23:20 UTC
Another build failure of 0.5.3 on OpenBSD 6.2 with clang-5.0.0:

    [1/13] /usr/ports/pobj/easyrpg-0.5.3/bin/c++  -DHAVE_FREETYPE -DHAVE_HARFBUZZ -DHAVE_LIBSNDFILE -DHAVE_LIBSPEEXDSP -DHAVE_MPG123 -DHAVE_OGGVORBIS -DHAVE_OPUS -DHAVE_SDL_MIXER -DHAVE_WINE -DHAVE_XMP -DSUPPORT_AUDIO -DUSE_SDL -DWANT_FMMIDI=2 -I/usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src -I/usr/local/include/liblcf -I/usr/X11R6/include/pixman-1 -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include/freetype2 -I/usr/local/include/harfbuzz -I/usr/local/include/opus -O2 -pipe   -I /usr/X11R6/include -DNDEBUG   -std=gnu++11 -MD -MT CMakeFiles/EasyRPG_Player_Static.dir/src/player.cpp.o -MF CMakeFiles/EasyRPG_Player_Static.dir/src/player.cpp.o.d -o CMakeFiles/EasyRPG_Player_Static.dir/src/player.cpp.o -c /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/player.cpp
    FAILED: CMakeFiles/EasyRPG_Player_Static.dir/src/player.cpp.o 
    /usr/ports/pobj/easyrpg-0.5.3/bin/c++  -DHAVE_FREETYPE -DHAVE_HARFBUZZ -DHAVE_LIBSNDFILE -DHAVE_LIBSPEEXDSP -DHAVE_MPG123 -DHAVE_OGGVORBIS -DHAVE_OPUS -DHAVE_SDL_MIXER -DHAVE_WINE -DHAVE_XMP -DSUPPORT_AUDIO -DUSE_SDL -DWANT_FMMIDI=2 -I/usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src -I/usr/local/include/liblcf -I/usr/X11R6/include/pixman-1 -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include/freetype2 -I/usr/local/include/harfbuzz -I/usr/local/include/opus -O2 -pipe   -I /usr/X11R6/include -DNDEBUG   -std=gnu++11 -MD -MT CMakeFiles/EasyRPG_Player_Static.dir/src/player.cpp.o -MF CMakeFiles/EasyRPG_Player_Static.dir/src/player.cpp.o.d -o CMakeFiles/EasyRPG_Player_Static.dir/src/player.cpp.o -c /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/player.cpp
    /usr/ports/pobj/easyrpg-0.5.3/Player-0.5.3/src/player.cpp:854:44: error: no viable conversion from 'std::ifstream' (aka 'basic_ifstream<char>') to 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >')
                            encodings = ReaderUtil::DetectEncodings(is);
                                                                    ^~
    /usr/include/c++/v1/string:1376:5: note: candidate constructor not viable: no known conversion from 'std::ifstream' (aka 'basic_ifstream<char>') to 'const std::__1::basic_string<char> &' for 1st argument
        basic_string(const basic_string& __str);
        ^
    /usr/include/c++/v1/string:1381:5: note: candidate constructor not viable: no known conversion from 'std::ifstream' (aka 'basic_ifstream<char>') to 'std::__1::basic_string<char> &&' for 1st argument
        basic_string(basic_string&& __str)
        ^
    /usr/include/c++/v1/string:1391:31: note: candidate constructor not viable: no known conversion from 'std::ifstream' (aka 'basic_ifstream<char>') to 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') for 1st argument
        _LIBCPP_INLINE_VISIBILITY basic_string(const value_type* __s);
                                  ^
    /usr/include/c++/v1/string:1415:5: note: candidate constructor not viable: no known conversion from 'std::ifstream' (aka 'basic_ifstream<char>') to 'initializer_list<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type>' (aka 'initializer_list<char>') for 1st argument
        basic_string(initializer_list<value_type> __il);
        ^
    /usr/local/include/liblcf/reader_util.h:44:62: note: passing argument to parameter 'database_file' here
            std::vector<std::string> DetectEncodings(const std::string& database_file);
                                                                        ^
    1 error generated.
    ninja: build stopped: subcommand failed.

**Comment by Ghabry** [comment] 2017-11-02 23:22
Update liblcf to 0.5.3.
Duplicate of #1292

**Closed** 2017-11-02 23:23 UTC
Labels: Building, Duplicate, Invalid
