### ISSUE TITLE
Battle 2k3: Weapons don't invoke skills

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1722] opened 2019-03-22 23:32 UTC
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
Use item：白虎杖
Normal use magic：狂風IV
After using the item, nothing happens. Calculate the round directly.

**Comment by Ghabry** [comment] 2019-05-25 22:34
Download link: http://www.cooltey.org/ping/game_page.php?id=mbl1

**Comment by Ghabry** [comment] 2019-05-25 22:53
This is basicly "Weapons that invoke skills (When you use them as an item) don't work"

**Comment by fmatthew5876** [comment] 2019-05-25 22:57
Weapons invoking skills is already fixed in master

**Comment by Ghabry** [comment] 2019-05-25 23:04
doesn't work for me

**Comment by fmatthew5876** [comment] 2019-05-25 23:07
Ok I'll have to check this one out. I tested a weapon which invokes healing magic in a test game and it worked. I didn't test this game specifically.

**Comment by Ghabry** [comment] 2019-05-25 23:10
I also didn't test the game, as I couldn't find the item ^^'.

I used a test game and just changed Club to do Poison.

**Comment by fmatthew5876** [comment] 2019-05-25 23:18
Ok I'm really confused now.

![pswd](https://user-images.githubusercontent.com/1198466/58375470-b9d67a00-7f21-11e9-8aa4-ed158e6061ed.png)

This works for me. I can use the item and do poison attack. I also tried to change poison attack to not do damage and only inflict poison, still works.

How is yours different?

**Comment by Ghabry** [comment] 2019-05-25 23:39
I found the problem.
It only fails when the item is not in the inventory but only equipped (when equipped and has a skill it will still appear in the item list as x1 for this actor)

**Comment by fmatthew5876** [comment] 2019-05-26 01:16
Ok, so I did that. Equipped my "POISON SWD". The actor with it equipped can use it, the other actor it doesn't appear.

So still I say it works for me!

What else is different in your case?

**Comment by s9060666** [comment] 2019-06-04 06:58
@fmatthew5876 
I don't know, I uploaded my log file to give you a try.
URL:https://drive.google.com/file/d/1-CtXZwo2iRYaicYhByxJLe1OLeJKNdC7/view?usp=drivesdk

**Comment by fmatthew5876** [comment] 2019-06-04 17:07
@s9060660

Do you have a save game with the item that I can use to reproduce the bug?

**Comment by s9060666** [comment] 2019-06-05 10:51
@fmatthew5876 
https://drive.google.com/file/d/1-Eb7b-keD--B39zzV3JUwO-T1LzvHOGR/view?usp=drivesdk
You can try this archive
Pick a character in battle:風鈴鈴->物品->白虎杖  I will see what I said.

**Comment by fmatthew5876** [comment] 2019-06-06 01:19
I can reproduce this.

The weapon is usable in the inventory from the 2nd actor. It is weapon 179 which invokes skill 145. The skill when invoked does nothing.

**Comment by fmatthew5876** [comment] 2019-06-06 02:13
Fixed by #1797

**Closed** 2019-06-07 20:02 UTC
Labels: Battle, Patch available
