### ISSUE TITLE
BGM of main title does not change when loading game with Maniacs 200128

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#3176] opened 2023-12-20 18:25 UTC
The game incorporates a custom save/load system with this version of Maniacs.

The process to test this is to get to the title screen, load game and note that the music is set from the map itself, this problem is not remedied until you change area, there is a fade out music and then starts the song of the new area.

I send it to @Ghabry privately as it is a Steam game for spring 2024.

Thank you very much.

**Comment by Mimigris** [comment] 2023-12-20 18:37
Seems similar to #3029 that was fixed in the continuous build months ago, just to be sure, have you checked if you were able to reproduce it on the continuous build?

**Comment by Br4ssman** [comment] 2023-12-20 18:50
I will provide some more information:
I have tested the continuous build, the result is the same, I will explain.

This is the song configured in this map and it sounds like this after passing the intro (new game):
https://github.com/EasyRPG/Player/assets/18174790/054d0425-1a58-4acf-8d0f-fc37a7d555c4

This is how it is configured:
![bgm_conf](https://github.com/EasyRPG/Player/assets/18174790/f3c29e74-4ace-492a-8373-5155502b11af)

If I proceed to resume a game and load normally, the main menu music continues to play:
https://github.com/EasyRPG/Player/assets/18174790/01c2212f-5ae3-40f3-b963-15a94f5bc93b

Here is a partial sample of the customised loading screen:
![custom_loadgame](https://github.com/EasyRPG/Player/assets/18174790/90890b53-2979-421e-9cd7-66aeb9edc025)

**Comment by Br4ssman** [comment] 2024-01-09 10:53
I add more missing details:

The title screen acts from a map (custom title menu), not the default of RPGM.
On the other hand, I'm trying to test if it has a solution from the Maker itself (playing BGM: OFF before loading), so far without success.

There is also no change if the music is configured from the map properties or if it is played from a specific event, so far the options are exhausted.

**Comment by Ghabry** [comment] 2024-03-11 19:41
@Br4ssman Sorry I'm not sure if I missed it but I cannot find the file you sent me. Can you send it me again?

**Comment by Ghabry** [comment] 2024-03-12 15:17
As @Mimigris already stated this was caused by an outdated version of the Player.

Though while testing the game I found a crash due to an incorrect value for a string picture https://github.com/EasyRPG/Player/pull/3195/commits/2259b561319befdbb58ab828e99358bbddb782c6

I added this to #3195  :)

**Closed by Ghabry** 2024-03-12 15:17 UTC
Labels: Audio, Invalid, RPG_RT Patches
