### ISSUE TITLE
Show Animation create a frame when there's no graphic in the animation

### ISSUE THREAD

**Issue by Br4ssman** [EasyRPG/Player#2058] opened 2020-01-28 15:54 UTC
**Name of the game**: Super Crystal Hunter
**Player platform**: Win 10 x64
**Describe the issue in detail and how to reproduce it**:

Sometimes we use this "trick" to make some specific flashes on some events.
It would be good try different ways of "empty animations" (e.g. flashes, play sounds, both) to tackle all these odd cases with Show Animations.

![animation](https://user-images.githubusercontent.com/18174790/73279985-2ced6a00-41ee-11ea-9e25-e7249e4999fc.png)

![emptyanimation](https://user-images.githubusercontent.com/18174790/73280909-7d18fc00-41ef-11ea-8b57-2a9b57b13f53.PNG)

**Comment by elsemieni** [comment] 2020-01-28 16:24
I'm going to provide more info and some corrections into this issue.

The issue is:
**Chara transparency is ignored when calling "Flash event" (Event and animation based) when screen tint is not 100,100,100,100.** 

- Tested in Nightly Player.
- It happens at any "flash event" command, from event command and animation.
- It does not happen with "flash screen" command. 
- This issue does not happen when no changes to tint made, or it's configued in 100,100,100,100.

**Comment by fmatthew5876** [comment] 2020-01-28 17:50
This should be fixed by #2052 

Can you please verify?

**Comment by elsemieni** [comment] 2020-01-28 18:44
> This should be fixed by #2052
> 
> Can you please verify?

Afirmative. PR #2052 fixes the issue until now.

**Closed** 2020-02-03 23:56 UTC
Labels: Animations, Color/Tone/Flash, Patch available
