### ISSUE TITLE
Hero transparenc in player test debbug

### ISSUE THREAD

**Issue by Soeufans** [EasyRPG/Player#2402] opened 2020-10-14 20:41 UTC
Hello!

heres a little issue about the "hero transparency" with player test

In player test mode:
You make the hero transparent with the command "hero transparency" an you make it HIDE to make it invisible, thats okay

But, when you load the game with F9, the hero remains invisible.

The same process occurs at viceversa:
If you save a game with the hero transparent, an you load the game from F9 when your hero is visible, the hero from the loaded game, turns visible

This only happens when loading the save with F9

Heres a sample:

[http://www.hellsoft.net/download/Hero_transparency.7z](url)

**Comment by fdelapena** [comment] 2020-11-08 13:46
Thanks. This is fixed in master, and duplicate of #2419

**Closed by fdelapena** 2020-11-08 13:46 UTC
Labels: Savegames
