### ISSUE TITLE
Parallel common events and parallel map events synchronization issues

### ISSUE THREAD

**Issue by trotterdotp** [EasyRPG/Player#662] opened 2015-12-06 10:18 UTC
[easyRPGdebugparall.zip](https://github.com/EasyRPG/Player/files/53118/easyRPGdebugparall.zip)
In this sample game, there is a parallel common event displaying the text "1" and a parallel map event displaying "2".

Using RPG_RT.exe 1.8.0 / 1.9.1 / 1.1.0, you should read:
---- > "1, 2"
then
---- > "1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2....."

Using player.exe:
---- > sometime it starts with 1, sometime it starts with 2. That's the first problem.
then
---- > "1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2.....". That's the second problem.

Parallel common event should maybe be prioritized?

Again many thanks for your work.

**Comment by Ghabry** [comment] 2015-12-06 11:55
That's one of this tricky timing bugs in the interpreter.
We are currently trying to compare Player with RPG_RT directly by logging event execution using DynRPG an then comparing it.
See #646. This is a good candidate for a test, thanks.  

This one won't be fixed as fast as your first one ;)

**Comment by Zegeri** [comment] 2016-02-07 15:42
Parallel common events are now executed first, so it should now always start with "1".
The pattern "1,2,1,1,2,1..." is caused by the way RPG_RT deals with messages. 83d0f56e74d used to replicate this behaviour. 

Just a curiosity. Have n parallel events displaying the numbers 1,2...n. If you've ever played around with Towers of Hanoi, you'll see that the pattern you get resembles the iterative solution of the Tower of Hanoi of n disks.

**Comment by Zegeri** [comment] 2016-02-09 10:29
I didn't include a patch for this in #753. Please, reopen this.

**Comment by Ghabry** [comment] 2016-02-09 10:52
Sorry, I interpreted the comment above incorrectly

**Comment by fmatthew5876** [comment] 2019-02-16 23:49
I just tried this master and it looks to be fixed. 

I get 1,2,1,1,2,1,1,2,1,1,2,...

**Comment by Ghabry** [comment] 2019-04-07 18:53
Tested it with 4 message boxes: Works.

But for this one I'm actually curious why the result is matching the hanoi-solution as noticed by Zegeri. Adding this to my "stuff for long nights"-list. xD

**Closed by Ghabry** 2019-04-07 18:53 UTC
Labels: Event/Interpreter
