### ISSUE TITLE
Abnormal state

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1490] opened 2018-11-07 12:35 UTC
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
www.mediafire.com/file/k0969lkmqqax6hu/
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Life recovery and mana recovery turns to decrease instead

**Comment by Ghabry** [comment] 2019-03-02 00:19
I revoke my patch for this because the IsPositive() handling makes this hard to implement without introducing regressions.
Will fix this as part of a BattleAlgorithm refactor that removes healing & positive.

**Comment by fmatthew5876** [comment] 2019-04-18 22:15
This is probably (?) fixed by #1726

**Comment by fdelapena** [comment] 2019-05-09 05:06
For completeness, I think here's the game download:

https://drive.google.com/drive/folders/0B74x5pGqP1-ZdzRoc1ZKMGFuZjQ

Source: https://home.gamer.com.tw/creationDetail.php?sn=2245636

**Comment by Ghabry** [comment] 2019-05-25 22:58
This probably means skills and the increase instead of decrease logic so I consider this as fixed when 1726 is merged.

**Closed** 2019-06-09 09:01 UTC
Labels: Battle, Patch available
