### ISSUE TITLE
Evasibe and critics attacks

### ISSUE THREAD

**Issue by lyehborealis** [EasyRPG/Player#832] opened 2016-03-19 20:14 UTC
Since I actualized easyrpg player almost every attack I do ends in evasive attack (but it still sounds like an attack) or critical hit. Please fix it.

And another bug is that some backgrounds don't work correctly (for example sometimes when I came into a battle where the background is a church, it doesn't, it's the plain predetermined)

Thanks.

**Comment by Ghabry** [comment] 2016-03-27 12:52
Closing because the 1st bug got fixed and the 2nd is a duplicate of #789

**Closed by Ghabry** 2016-03-27 12:52 UTC
Labels: Battle, Duplicate
