### ISSUE TITLE
The Way Part 1: Scenery scroll speed problem, midis don't play

### ISSUE THREAD

**Issue by BiggerJ** [EasyRPG/Player#1147] opened 2017-04-21 11:15 UTC
**Name of the game:** The Way Episode 1

**Player platform:** Wii

**Describe the issue in detail and how to reproduce it:** In The Way Episode 1 ( http://www.crestfallen.us/download.html ), the scenery/background moves too fast relative to actual sprites and movement boundaries when the camera moves left (this happens during both gameplay and cutscenes - the latter can be seen during the 'Nothing can replace her...' text during the opening). For some reason, the background during the opening's 'Wanderers...' text is misaligned from the start, both horizontally and vertically. For those unfamiliar with The Way, it has many backgrounds that are pre-rendered images. Also, midis won't play - a 'Couldn't play BGM' error appears at the top of the screen whenever one is supposed to play. And a minor quirk - WAVs at least sometimes keep playing to the end (but not looping, even if they were looping before) when I press the reset button on the front of my Wii to return to the game's title screen.

---
- [x] scenery/background moves too fast when camera moves left
- [x] background during the opening's 'Wanderers...' text is misaligned
- [x] midis won't play [NotABug]
- [x] waves keep playing when returning to title scene (using F12/reset)

**Comment by carstene1ns** [comment] 2017-04-21 14:42
Hi, thanks for the bug report!
About movement/text issues: We will run this game to check for them
About the MIDI music: Did you install the instrument files? Put the content of [this](https://github.com/Ghabry/timidity_gus/archive/master.zip) archive into `/data/wildmidi` folder (toplevel, not where the `boot.dol` is located) on your Wii`s SD Card or USB drive.
About Sounds not stopping when returning to title screen: This is a known issue and will hopefully be fixed in a needed audio system refactor soon.

**Comment by Ghabry** [comment] 2017-04-22 00:44
This is a regression. Bisect result:
```
7f83a3bf0a93d2ff5fcde27a721939a4a85e776a is the first bad commit
commit 7f83a3bf0a93d2ff5fcde27a721939a4a85e776a
Author: scurest <scurest@users.noreply.github.com>
Date:   Sun Mar 26 13:48:12 2017 -0500

    Handle scrolling of parallax BGs with new method
    
    ie. using the values from GetParallaxParams.
    
    Also, Game_Map now interacts with the parallax variables only
    through the function is Game_Map::Parallax.

:040000 040000 8007301ae014c078789d8ba2877725706845b276 13eaead9c316cb1531a2d58ecb1f176e21441c67 M      src
```

**Comment by BiggerJ** [comment] 2017-04-22 00:49
"About movement/text issues: We will run this game to check for them"
Oh, none of the issues were with text. I was just mentioning certain parts of the text that appears during the opening cutscene as reference points to describe when certain problems could be seen.

**Comment by carstene1ns** [comment] 2017-04-22 18:27
Good to know that there are no text issues.
@Ghabry has found the reason for the weird scroll behaviour and provided a fix.
You can download the new Wii build [here](https://ci.easyrpg.org/job/player-wii/lastSuccessfulBuild/artifact/builds/wii/easyrpg_wii.zip).

**Comment by carstene1ns** [comment] 2017-08-12 21:38
All background movement related issues seem resolved in current master.
We will track the stopping of Sound Effects on reset in #1120.
Closing, feel free to reopen if needed.

**Comment by carstene1ns** [comment] 2017-08-12 21:59
Well, given this was an easy fix, reopening this again… 💃

```diff
diff --git a/src/player.cpp b/src/player.cpp
index 73cec0ec..0b16ce3d 100644
--- a/src/player.cpp
+++ b/src/player.cpp
@@ -289,7 +289,9 @@ void Player::Update(bool update_scene) {
 		reset_flag = false;
 		if (Scene::Find(Scene::Title) && Scene::instance->type != Scene::Title) {
 			Scene::PopUntil(Scene::Title);
+			// Fade out music and stop sound effects before returning
 			Audio().BGM_Fade(800);
+			Audio().SE_Stop();
 			// Do not update this scene until it's properly set up in the next main loop
 			update_scene = false;
 		}
```

**Closed** 2017-10-13 12:08 UTC
Labels: Audio, Bitmaps, Patch available, Wii
