### ISSUE TITLE
The Sacred Tears TRUE: Character doesn't move after (very long) intro

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#579] opened 2015-09-07 21:23 UTC
The first time the character is playable after the intro (in the house) the movement keys don't work.
Only Escape and Shift do. The workaround is to hold Shift, then moving works.

KeyInputProc problem?

Can't provide a Savegame because the created savegame is corrupted (#556)

Demo: http://nyu-media.com/sacred-tears-true/

The LMT file is "encrypted", decryption code (Python):

``` Python
#!/usr/bin/env python
import sys
with open("RPG_RT.lmt", "rb") as f:
    with open("RPG_RT.lmt2", "wb") as g:
        b = f.read(1)
        while b != b"":
            args = [chr(ord(b)-1 if ord(b)>0 else 255)]
            if (sys.version_info > (3, 0)):
                args.append("latin-1")
            _ = g.write(bytes(*args))
            b = f.read(1)
```

**Comment by carstene1ns** [comment] 2015-09-14 16:40
Just a short addition, this ruby script can also be used to decrypt and crypt the file:hammer::

```ruby
#!/usr/bin/env ruby

tree = IO.read('RPG_RT.lmt')
chars = tree.unpack('c*')
dir = chars[0] == 11 ? -1 : 1
chars.map! {|c| c + dir}
tree = chars.pack('c*')
File.open('RPG_RT.lmt','w') {|f| f.write tree}
```

**Comment by Zegeri** [comment] 2015-09-17 17:00
I can't reproduce this. I can move without problems inside and outside the house.

**Comment by Ghabry** [comment] 2015-09-17 17:28
That's interesting. Maybe your parallel process fix fixed this, too.
Checking later

**Comment by fdelapena** [comment] 2015-09-18 03:54
I can reproduce it in upstream master. It does not happen always, however. I got blocked in some case after navigating a bit the menu and returning to the game.

**Comment by Ghabry** [comment] 2015-09-18 10:27
So the important part is to fix #556 to get a proper savegame for easier testing.

**Comment by carstene1ns** [comment] 2015-09-18 20:24
Here is a savegame saved in RPG_RT right after the opening: http://f4ke.de/dev/easyrpg/TSTT/Save03.lsd

**Comment by carstene1ns** [comment] 2015-10-04 15:33
@Zegeri: Is this also fixed by 0c3fb4cb2cdc08209e9fd54b7593e84df9f83558?

**Comment by Zegeri** [comment] 2015-10-04 15:50
I'm sure that commit can't fix hangs. But it seems that exiting the house after loading your save file would cause the characters to disappear. Some other commit in my branch must have fixed it.

**Comment by Ghabry** [comment] 2015-10-06 19:16
Another game with exactly the same issue (you can't move but you can open the custom menu):  Standstill Girl (aka Teitai Shoujo)

**Comment by fdelapena** [comment] 2015-10-06 21:28
I can "unblock" the actor movement by pressing X/Esc, as the menu is not working currently (#433).

**Comment by Ghabry** [comment] 2016-01-21 19:10
Closing this one because it works in Sacred Tears...

**Comment by carstene1ns** [comment] 2019-03-10 22:13
This one has been broken in #1601. Resetting milestone.

**Comment by fmatthew5876** [comment] 2019-03-12 00:26
Still broken in #1687

**Closed** 2019-03-12 21:54 UTC
Labels: Event/Interpreter, Hang, Patch available
