### ISSUE TITLE
Ahriman's prophecy doesn't recognize ESC button

### ISSUE THREAD

**Issue by cristianceron** [EasyRPG/Player#433] opened 2015-03-09 23:08 UTC

**Comment by cristianceron** [comment] 2015-03-09 23:12
Download the game here:
http://aveyond.com/games/ahrimans-prophecy/
I don't think there's problems since is freeware.

**Comment by Zegeri** [comment] 2015-03-10 22:22
The problem is in the Common Event 48 "Call CMS". It's a parallel process triggered by the switch 0453 "Call CMS". When the player press ESC the following lines are executed:
```
  Switch Operation [0453:Call CMS] OFF
  Switch Operation [0988:Call CBM] ON
  Call Event: Call CBM
  Break Loop
```
After 0453 is switched off, easyrpg-player stops the processing of this common event and everything after it isn't executed. In RPG_RT.exe, every line is executed.

**Comment by Ghabry** [comment] 2015-03-10 22:30
The instant termination of Parallel Processes is by design because RPG_RT does this. At least for map events, maybe it's different for Parallel Common events? -.-

**Comment by scurest** [comment] 2015-03-12 05:10
Seems to be like Ghabry says. But wait, it gets weirder.

Make an event E that flips Switch 1 on when you trigger it, a common parallel event conditional on Switch 1 with the commands

    flip Switch 1 off
    add 1 to Variable 1
    wait 0.1 seconds
    add 1 to Variable 1

and an event to check the value of Variable 1.

After triggering E 0,1,2,3,4,... times, the respective values of Var 1 afterwards are 0,1,3,5,7,... !

**Comment by Zegeri** [comment] 2015-03-12 09:15
That's correct, the common event won't stop even after switching its trigger off until the wait command. But when you activate its trigger again, it won't start from the beginning, but from its last position, i.e. the wait command. That's why it'll run the two variable operations the second time you run it.

**Comment by Zegeri** [comment] 2015-03-24 16:31
This issue and the whole common event stuff should be fixed in my [development branch](https://github.com/Zegeri/Player/tree/development). Now let's make sure there are no regressions.

**Comment by fdelapena** [comment] 2015-03-26 14:15
Tested with a couple of games with unrelated issues (Warrior Saga, Desolate City), all of them are working as usual (with their own bugs).

Maybe this game is worth to test due its complexity (action RPG, menus...):
http://www.pyxosoft.com/downloads/zelda_links_awakening_100.zip

**Comment by Ghabry** [comment] 2015-03-26 14:16
Links awakening actually has a strange bug at the beginning. The princess moves very slow and is off by one tile until she is close to link.
Not sure if this got already fixed by accident.

**Comment by Ghabry** [comment] 2015-05-15 22:59
Was that fixed by @Zegeri latests KeyInput changes?

**Comment by fdelapena** [comment] 2015-05-15 23:32
Esc button does not work in upstream master yet. Development branch changes are not merged.

**Comment by Zegeri** [comment] 2015-05-16 06:47
This is fixed in my interpreter branch, but it breaks other things.

**Comment by fdelapena** [comment] 2015-05-16 22:09
Online version for testing. Note sometimes fails the 1 key for some reason, and seems to work fine on Desktop:

For latest pull request:
https://easy-rpg.org/play/index-pr.html?game=ahrimans_prophecy
For upstream master:
https://easy-rpg.org/play/?game=ahrimans_prophecy

**Comment by fdelapena** [comment] 2015-10-05 19:01
It looks like this issue regressed. Esc/X is not opening the menu anymore.

**Comment by Zegeri** [comment] 2015-10-05 21:10
My mistake. The changes in src/game_interpreter.cpp in 30a3b58c7 shouldn't be there. The main_flag check must be there (see #578).

**Comment by carstene1ns** [comment] 2015-10-06 01:43
I can confirm adding the `main_flag` check back in makes the menu work again.
This also affects TSTT, btw. You currently also cannot use the ESC menu.

**Closed** 2015-10-22 10:26 UTC
Labels: Events, Interpreter, Patch available
