### ISSUE TITLE
emscripten touch support is intented?

### ISSUE THREAD

**Issue by krmbn0576** [EasyRPG/Player#2694] opened 2021-11-15 07:14 UTC
In 0.7.0, Key Input Proc (Maniac Patch) for `mouse` is supported, and emscripten build supports touches.

https://github.com/EasyRPG/Player/blob/dfbad2001d17eb6bbb503c1df0028353de2b9dce/src/system.h#L58-L60

https://github.com/EasyRPG/Player/blob/d3e3a1317e0f9bd701784f76179b1ac73ee3b35f/src/input_buttons_desktop.cpp#L154-L157

However, I tested this and did not work.

fingers touch input is intented? or not implemented yet?

**Comment by Ghabry** [comment] 2021-11-15 13:54
Touch instead of Mouse is not implemented but I totally see that this would be the expected behaviour (at least for Left & Right Touch, Cursor position is a different topic...)

One Touch: Left click
Two Touch: Right click
Three Touch: Middle Click

Converting it to a mouse cursor is more tricky, maybe just use the last touch position and when the finger moves on the screen the cursor moves?

The code you found is "Touch for decision & cancel".

This can be enabled with the option ``--enable-touch`` or ``?enable-touch`` in emscripten. With this option you can e.g. continue messages boxes with a touch (the same applies to ``--enable-mouse`` for click to continue).

Note that these options could conflict with the KeyInput support because One Finger Touch is then detected as both Decision and Left-Click.  (when I fix this issue)

**Comment by Ghabry** [comment] 2021-11-15 22:37
Hmm, short term solution is checking for ``ONE_FINGER``, ``TWO_FINGERS`` and ``THREE_FINGERS`` in Ineluki and Maniac when mouse buttons are checked.

This will not help with mouse cursor movement via touch but at least makes the finger working :thinking: 

(Long term solution would be a better integration in the normal Input class)

**Comment by krmbn0576** [comment] 2021-11-15 23:45
However, the strange thing is that the touched coordinates can be obtained by the `GetMousePosition` command, even though it does not appear to be implemented yet. In other words, `mouse_pos` already supports finger touch!

Why don't MouseButtons support finger touch?

**Comment by Ghabry** [comment] 2021-11-15 23:49
I checked the documentation:

```
which may be SDL_TOUCH_MOUSEID, for events that were generated by a touch input device, and not a real mouse. You might want to ignore such events, if your application already handles SDL_TouchFingerEvent.
```

So mouse motion and touch motion is sent through the same event and we do not check the ``which``. Meaning this works already by accident :sweat_smile:

**Comment by krmbn0576** [comment] 2021-11-16 00:00
I see, it was an accident after all 😆  I understood that `key input proc for touch` is not yet supported. thx

**Comment by Ghabry** [comment] 2021-11-18 20:29
@krmbn0576 
You can "fix" it by deleting these two lines here and recompiling the Player.

https://github.com/EasyRPG/Player/blob/master/src/sdl2_ui.cpp#L642-L643

-----------

This will not be changed upstream. I work on a better fix instead but this takes longer :)

**Comment by krmbn0576** [comment] 2021-11-19 04:51
thx, I tested it.

Key Input Proc 1005 (Left Click) was activated when the screen was touched, but other events seem to be unsupported.

I can't think of a way to implement the wheel event, but `2 Fingers = Right Click` should be supported.
Therefore, I will not adopt this fix :->

**Comment by Ghabry** [comment] 2021-11-19 07:55
Okay so the mouse emulation is junk.  Good to know. :D

**Comment by Ghabry** [comment] 2022-12-09 00:42
I found a way to properly detect N fingers, making this fully compatible with the mouse input. (only gestures for "scrolling" won't work)

Will be part of 0.7.1 (when its done :sweat: )

**Closed** 2023-03-16 19:37 UTC
Labels: Patch available, Emscripten, Input
