### ISSUE TITLE
Android A button

### ISSUE THREAD

**Issue by hiro1986** [EasyRPG/Player#729] opened 2016-01-19 10:45 UTC
2000&2003 Start by enter key not started.

Ikusaden mairu did not attack：(

error message
Branch：started using key not implemented

**Comment by Ghabry** [comment] 2016-01-19 11:04
Thx for reporting. Closing because this is a duplicate of #714 . We are working on it :)

**Closed by Ghabry** 2016-01-19 11:04 UTC
Labels: Duplicate

**Comment by fdelapena** [comment] 2016-01-24 18:58
@hiro1986 the issue has been fixed in #736 and will be included in the next Player release.
