### ISSUE TITLE
Open menu black frequency

### ISSUE THREAD

**Issue by s9060666** [EasyRPG/Player#1761] opened 2019-05-07 07:45 UTC
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android 
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
After turning on the menu, it will be directly black. Nothing can be done.

**Comment by fdelapena** [comment] 2019-05-07 19:09
Thank you for the bug report.

Some notes:

- Game website: https://sites.google.com/site/mrjxrmplan/game_mf2
- Game download (ver. 1.15): https://www.dropbox.com/s/mnm1eav9qa27cif/mf2.rar?dl=1
- This game uses custom menus: https://i.imgur.com/feeKLDE.jpg

**Comment by Ghabry** [comment] 2019-05-25 22:13
This is a post 0.6 regression!
In 0.6 the menu works and doesn't blackscreen.

**Comment by fmatthew5876** [comment] 2019-05-25 23:05
Here is a savegame after the intro. Press ESC and see a black screen

[Save01.zip](https://github.com/EasyRPG/Player/files/3219828/Save01.zip)

**Comment by fmatthew5876** [comment] 2019-05-25 23:40
This looks like some interpreter bug

Common event 5 is parallel has the key input proc to trigger off of ESC. When this event is triggered, you get teleported to map 5.

On Map5, an autostart map event is supposed to take over. But it looks like common event 10 somehow keep running over and over in the foreground, preventing it from executing. 

Digging deeper...

**Comment by fmatthew5876** [comment] 2019-05-25 23:48
Test Cases
==========

1. Setup EV01 autostart
```
Wait 0.0s
```

EV02 autostart
```
Shake Screen
```

Result: Screen shakes

2. Delete EV01,

Setup CE01 as autostart
```
Wait 0.0s
```

Result: Screen Shakes

**Comment by fmatthew5876** [comment] 2019-05-25 23:50
Test Cases 2 - Messages
=================

1. EV01 autostart `Msg: EV01`
EV02 autostart `Msg: EV02`
CE01 autostart `Msg: CE01`

Result: EV01, CE01, EV01, CE01, ...

**Comment by fmatthew5876** [comment] 2019-05-26 00:15
Test Cases 3 - Exec Order
=====================

Here's a way to see what order these events execute in

EV03 parallel
```
Var1000 = 1
EraseEvent
```

EV01 autostart
```
[Var1000] = 1
Var1000 += 3
```

EV02 autostart
```
Var1000 += 1
[Var1000] = 1
Var1000 += 2
```

CE01 autostart
```
Var1000 += 2
[Var1000] = 1
Var1000 += 1
```

Result: The following variables have the value 1
1, 6, 8, 12, 15, 18, ..

Which means we execute

EV01, CE01, EV02, CE01, CE01, CE01, CE01, ..

Hypothesis
=========

PreUpdate:
The waiting flag for both EV01 and EV02 gets setup, but since they are foreground events they don't execute.

First Frame:
waiting flag causes EV01 to execute first. Then CE01 runs. Then waiting flag for EV02 causes it to go.

Then CE01 runs forever

**Comment by Ghabry** [comment] 2019-05-26 00:24
For case 3 the execution order is according to event tracer:

```
EV03
[transition in]
EV01
CE1
EV02
CE1
CE1
CE1
.....
```

Common autorun events have no yield (compared to parallel common events) when they reach the end. They just rerun again in the same frame.

**Comment by fmatthew5876** [comment] 2019-05-27 19:43
Test Cases 4 - Teleporting
====================

1.

Map 1 EV01 `Teleport Map2`
Map2 EV01 `Msg: EV01`
CE01: `Msg: CE01`

Result:

Teleport, CE01, EV01, CE01, EV01

2. 

Map 1 EV01 `Teleport Map2, Msg: OldEV01
Map2 EV01 `Msg: EV01`
CE01: `Msg: CE01`

Result:

Teleport, OldEV01, CE01, EV01, CE01, EV01

**Comment by fmatthew5876** [comment] 2019-05-27 20:26
Test Cases 7 - Face Graphics Reset
=============================

1. EV01 autostart
Page 1 `Msg: Bye`
Page 2 autostart `Msg: Pre, Change Face, Msg: Hi, Call ThisEvent[1], EraseEvent`

CE01 autostart `Msg:CE01`

Result:

"Pre", "Hi (face)", "Bye (face)", "CE01 (face)" :exclamation: "CE01, "CE01", ...

Conclusions
==========

Normally when a foreground event runs the face graphic is cleared. However when both a common and map event run. They both get pushed onto the stack, so the face is cleared twice during the pushing but does not get cleared when the common event runs after the map event finishes.

So whether or not an autostart common event will clear the face graphic depends on if a map event ran the same time or not.

**Comment by fmatthew5876** [comment] 2019-05-27 21:09
I've retested the game with #1779 - bug is fixed

**Comment by Ghabry** [comment] 2019-06-07 20:39
Bug is fixed, so I already close this as part of 0.6.1 (the improved fix lands in 0.6.2)

**Closed by Ghabry** 2019-06-07 20:39 UTC
Labels: Event/Interpreter, Patch available

**Comment by s9060666** [comment] 2019-06-08 07:48
@Ghabry 
So this has to wait until 0.6.1 to fix it?

**Comment by Ghabry** [comment] 2019-06-08 07:52
@s9060666 

This works with the latest APK / latest computer version.

When we close a bug it is always fixed in the latest version.

The next official release is 0.6.1 which is not released yet.
