### ISSUE TITLE
Audio - Single sounds can't be stopped by playing them multiple times with volume of 0

### ISSUE THREAD

**Issue by TitanKaempfer** [EasyRPG/Player#3276] opened 2024-09-29 18:59 UTC
**Name of the game:** EasyRPG-NoSoundStop-Example
**Player platform:** Windows, continuous build of EasyRPG Player
**Issue:**
Normally sounds get "replaced" when there is 5 sounds of the same sound file playing. This can be used to stop one specific sound effect by playing the sound with a volume of 0, 4 additional times.
If attempted to do so in the current EasyRPG build, the sound will not stop as it should, breaking systems in which only one specific sound should stop playing. (For example an ambient sound on map change, without stopping a door sound) 

The included example game features two NPCs, a golem and a dragon. The golem will play a long sound effect and the dragon will play the same sound effect with a volume of 0. In the normal RPG_RT.exe the dragon will stop the sound played by the golem, this behaviour does not exist in the EasyRPG player.

**Download to the example game:**
[EasyRPG-NoSoundStop-Example.zip](https://github.com/user-attachments/files/17180801/EasyRPG-NoSoundStop-Example.zip)

**Comment by Ghabry** [comment] 2024-09-29 20:36
Thanks for the report and the test case however it is a duplicate of #1356 so I have to close it.

**Closed by Ghabry** 2024-09-29 20:36 UTC
Labels: Duplicate
