### ISSUE TITLE
Asunana: Hiragana password input problems

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1721] opened 2019-03-22 16:01 UTC
Name of the game: Asunana 1.02

#### Attach files (as a .zip archive or link them)
[Save01.lsd.zip](https://github.com/EasyRPG/Player/files/2997279/Save01.lsd.zip)

#### Describe the issue in detail and how to reproduce it:
Use Walk through walls to move to the room to the left and talk to the ball.

Enter as password "ござる". Works for me but no idea what is supposed to happen.
Can't see a difference to RPG_RT.

**Comment by Ghabry** [comment] 2019-03-23 15:12
Well I tested this and can't find a difference to RPG_RT, keeping this open for a day or two.

**Comment by Ghabry** [comment] 2019-03-23 15:19
minor savegame loading bug: When loading the save in RPG_RT the event in the midle of the room for saving changes to a red ball when talking to it, which shouldn't happen.
Probably something not correctly saved.

**Comment by carstene1ns** [comment] 2020-03-17 03:01
Closing, because cannot be reproduced.

**Closed by carstene1ns** 2020-03-17 03:01 UTC
Labels: Savegames
