### ISSUE TITLE
The back button not working for Samsung Galaxy S6

### ISSUE THREAD

**Issue by craynafinal** [EasyRPG/Player#919] opened 2016-07-01 08:11 UTC
Name of the game: Danganronpa Another

Player platform: Android

Describe the issue in detail and how to reproduce it:

I am using a Samsung Galaxy S6 and it appears that the back button is not working for button mapping. I need a shift key to play the game but I tried many times but I can't get the button mapping submenu that should be triggered when pressing the back button.

**Comment by Ghabry** [comment] 2016-07-01 09:15
We got reports by some users that this gets fixed by doing a system upgrade of your Galaxy S6 to the latest version.
The problem is that we use deprecated Ui stuff which works on all phones except the S6 >.<

**Comment by jsl87** [comment] 2016-07-01 22:24
Thanks for your reply, I also thought about the android version and it seems like mine is the latest version, 6.0.1. I ran check for updates in setting but it says nothing to do. Did you get the reports from people using 6.0.1?  Please let me know.

**Closed** 2016-08-27 20:19 UTC
Labels: Android
