### ISSUE TITLE
Embric of Wulfhammer's Castle: Game occasionally freezes in 993 Anti-Paladins battle

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#875] opened 2016-04-26 10:16 UTC
EasyRPG occasionally freezes specifically during the 993 Anti-Paladins battle in this game.
To be more exact, the game technically remains responsive, but the battle system itself is stuck, meaning that the ATB gauges do not refill and thus it is impossible to actually do anything. As far as I can tell, there is no way to get around the problem.

* Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
* Savegame: https://www.heavylobster.com/files/Save07.lsd

To reproduce, walk towards the east to start the encounter after going through some dialogue (the 'Zhen die without explanation' option is fastest). Then just keep battling until the freeze occurs. It doesn't seem to be caused by any particular player actions (can be reproduced with autobattle) and it doesn't seem to occur every single time I do the battle either, so it may take several attempts to reproduce. It is still quite common, though.

(this was tested with latest git as of this typing)

**Comment by carstene1ns** [comment] 2016-07-24 21:05
As we found out today, this is a battle system deadlock caused by a skill reviving a party member.
This case is already handled for items, though.

**Comment by Ghabry** [comment] 2016-07-26 00:07
Have a fix for this but have to do more testing.

**Comment by Ghabry** [comment] 2016-07-26 15:51
I know in the meanwhile why this doesn't affect Ara Fell: As Vampires Dawn 2 this game uses battle animations for the battlers instead of normal animated battlers. Have to compare the code to find what we do different there.

**Closed** 2016-07-30 03:06 UTC
Labels: Battle, Hang, Patch available, Testcase available

**Comment by Zegeri** [comment] 2016-08-04 10:36
Now the Anti-Paladins don't disappear when they die.

**Comment by Ghabry** [comment] 2016-08-04 11:59
Uh that's bad, will fix it :(
