### ISSUE TITLE
Embric of Wulfhammer's Castle: 2 actors already dead in the beginning of a battle

### ISSUE THREAD

**Issue by Siltala** [EasyRPG/Player#949] opened 2016-07-25 17:21 UTC
You asked for more bug reports on IRC, so here we go :)
*   Game download: https://aeresland.net/EmbricDELUXE_2.2.2.7z
*    Savegame: https://www.heavylobster.com/files/Save07.lsd

Siding with the Anti-Paladins in the 999 Anti-Paladins event results in a battle in which two actors in the party are already dead in the beginning of the battle, which definitely isn't supposed to happen. Interestingly, the game actually reports one of the actors having 509 HP left despite being dead.

Screenshot taken at the beginning of combat:
![screenshot from 2016-07-25 20-10-15](https://cloud.githubusercontent.com/assets/2873449/17110276/e1c5aaa6-52a4-11e6-822a-7abd2ddbab34.png)

To reproduce, walk towards the east to start the encounter. Pick option one or three in the dialogue, and then choose to side with the Anti-Paladins. The problem will immediately become apparent.

For what it's worth, I also tested completing the Anti-Paladins arc and repeating it after the ensuing ending, and the problem persists still.

**Comment by Ghabry** [comment] 2016-07-26 00:06
Closing as not a bug because it looks exactly the same when loading in RPG_RT. I guess you created this savegame with an old version of EasyRPG Player which had bugs in filling the states.

![screenshot_20160726_020449](https://cloud.githubusercontent.com/assets/1331889/17121619/59358720-52d5-11e6-8a92-2668a48b8f7e.png)

Fixed your savegame so it loads in RPG_RT (or start a new game in EasyRPG, then it will be correct ;)):
[Save08.zip](https://github.com/EasyRPG/Player/files/382742/Save08.zip)

**Closed by Ghabry** 2016-07-26 00:06 UTC
