### ISSUE TITLE
Battle RM2000/2003 - Graphic / Music / Sound Message Display issues: Remaining

### ISSUE THREAD

**Issue by Albeleon** [EasyRPG/Player#1371] opened 2018-06-10 02:30 UTC
Issues related with Graphics, Music, Sound and Message Display mainly focused for RPG Maker 2000. A few of them also apply to RM2003 just by extension:

1. Battle Events:
- [x] 1.1: RM2000: When a Battle Event is executing (whether by "Wait seconds" or an animation loading), the window battle screen should be empty and you shouldn't be able to access commands.
- [x] 1.2: RM2000: Animations executed in a battle event should not wait until the animation is over when the option "wait to end" is selected.
- [x] 1.3: RM2000 + RM2003: When an enemy dies in a event, it has different effects depending of whether it dies by HP damage or status condition = Death. In the first one, it gradually disappears with monster dying sound. In the second one, it just disappears inmediately.
- [x] 1.4: RM2000: If an event page makes all their actions before the message display window is needed to display, the status window should be able to refresh inmediately without skipping a frame (for example, if "Event page: (Turn 0x + 0); DecreaseHP(Player1, 999, Dead)".

2. Message Display:
- [x] 2.1: RM2000: If no hero party is ready to attack and they can't choose actions, the command options shouldn't flash for a few frames.
- [x] 2.2: RM2000: If a character recovers themself from a negative condition, the message should be printed and not empty.
- [x] 2.3: RM2000 + RM2003: The battle command window (both left [manual, automatic, escape] and right [attack, skill, defend, objects]) should move smoothly of position from one another instead of inmediately (in RM2003, type of Window Battle Screen B and C).
- [x] 2.4: RM2000 (not tested in RM2003): If you have the "special skill name" (to give your character a different name to the skill command) checkbox unmarked, it should show the default skill name instead of what is inside.
- [x] 2.5: RM2000: If the second line of a Skill is not empty: 1. The first line should have a pause before the second line is printed, and 2. The animation should only start when the second line is printed.
- [x] 2.6: RM2000 (issue #1102 ): When an enemy dies, a message should be displayed right after the attack inside the same message.
- [x] 2.7: RM2000 + RM2003: The Victory message should have pauses after each line. The first line with the victory message has a longer pause than the others (in RM2003 only the first line should have a pause).
- [x] 2.8: RM2000: If an enemy causes a condition (poison, sleep, etc.) and fails, the message should be it failed/missed.
- [x] 2.9: RM2000: When an ally receives damage result that is more than 0, the screen should shake a little bit.
- [x] 2.10: RM2000: When a skill or object is used, the skill/object window should stay as it is static and the enemy/ally window over it, instead of hiding the skill/object window.
- [x] 2.11: RM2000: When an enemy uses a technique/ability, the animation, while it doesn't show any graphic or flashes, it shows the sound, and when it ends the result appears. It doesn't play the generic "attack" sound.
- [x] 2.12: RM2000: Using an object that restores SP displays the message with the amount -1 (it recovers the normal SP though).
- [x] 2.13: RM2000: When pressing CANCEL when selecting an enemy target, it should return to the previous window / state, not to SelectCommand. Just like AllyTarget.
- [x] 2.14: RM2000: Critical hits from attacks should be displayed.
- [x] 2.15: RM2000: The conditions caused by a weapon attack are different from the ones selected in RPG_RT (i.e. a weapon with Poison and Blindness, causes Death).
- [x] 2.16: RM2000: If you have one instance of an object and it's the last one in the list, in the battle, when you use it and return to the item window, for a frame you can see the cursor in that position (which now it's empty and shouldn't be accesible) before going back to a normal position. Logically it's fixed, but graphically it's an awkward frame change.
- [x] 2.17: RM2000: When an attack heals states, that should be in battle_algorithm, instead of being treated in the results. Also, it is possible for an attack to heal a state, and right after cause that state again.
- [x] 2.18: RM2000: The enemy flash that indicates it's their turn, it only appears once, and it appears before the condition_heal, not when it starts their action.
- [x] 2.19: RM2000: When going to the skill battle menu, only when you go from SelectCommand the index should go to the first one (0). If you press CANCEL after selecting an enemy, it should keep in the same position.
- [x] 2.20: RM2000: Only active enemies should have their actions defined for a turn: hidden or dead ones shouldn't.
- [x] 2.21: RM2000 + RM2003: Implement Confusion and Provoke, it defines their actions, and checks when it's the character's turn whether it's been affected by them or not in the same turn.
- [x] 2.22: RM2000: When BattleActionState ConditionHeal, it only prints the last message out of all the messages. Latter states have priority over former states. Remaining message states have priority over recovered message states.
- [x] 2.23: RM2000 + RM2003: When screen shakes in a battle, the borders should be black.
- [x] 2.24: RM2000 + RM2003: Implement NormalDual attack, and make a double attack by an enemy or ally with a "Double attack" weapon NormalDual.
- [x] 2.25: RM2000: Skills and items that affect whole groups should only reduce the item count or SP once. Check too if a weapon that decreases SP reduces when it hits double, everyone or misses.
- [x] 2.26: RM2000 + RM2003: When calculating an actor's state probability, the armor state resistance should be also taken. If there are many armors with state protection of the same type, only the one with the most resistance will be taken, they don't stack.
- [x] 2.27: RM2000 + RM2003: If all the player party is in a state that has Restriction NoMove and has a 0% chance of recovery (the physical recovery doesn't matter), it's a game over.
- [x] 2.28: RM2000 + RM2003: If a battler is thrown a state again, the turn count for recovery probability should be the same with no changes, it shouldn't "reset". Probability of state recovery probability should also be only each X turns, not each turn after it surpasses X turn. When the battler is first thrown into a state, if it has 1 turn recovery or more, there should be an extra turn where they do nothing (afterwards it's always a multiple. With 0 turn it happens even in the first turn).
- [x] 2.29: RM2000: Print "attribute resistance / weakness" result message in skills when it's successful, and make sure if it's active that its increase/decrease is given the same success features as a state (if the parameters fail in a way that ignores the state, it ignores this too; if it cannot provoke any attribute UP/DOWN effect, it doesn't turn the attack in a success).
- [x] 2.30: RM2000 + RM2003: Mark as "unusable" the objects of type "special" by a character who can't use them. With medicine, if the character unusable is the target, then the attack misses.
- [x] 2.31: RM2000: Items that miss shouldn't print any message at all.
- [x] 2.32: RM2000 + RM2003: When throwing an item to a dead character without the "only k.o." option, the target is still the dead person, it doesn't change, and the attack can succeed (it can still recover SP and states like Dead for example and resurrect, even if no HP will be taken if it doesn't cure Death). An item fails if "only k.o." is checked and it's thrown to an alive actor, or if it doesn't recover any HP, SP or condition.
- [x] 2.33: RM2000 + RM2003: A skill that costs SP and recovers SP, it can recover the SP that spent in that same skill.
- [x] 2.34: RM2000 + RM2003: Modify "to_hit" parameter for physical attacks and techniques: Physical Dodge evasion of the target's armors (doesn't stack), if the target can't move (100% to_hit) and if the source is in a state that loses accuracy. If a skill attack misses by chance, it doesn't execute the state/attribute operations.
- [x] 2.35: RM2000 + RM2003: When an absorb skill attack, if HP or SP are selected and the result is 0, the skill attack misses in its entirety, but it can still hit if they are unselected and the other stat decrease are 0 if the skill does other things (states, attribute resistance, etc.). If it doesn't absorb, the attack misses if it doesn't have HP selected but yes SP and it's 0.
- [x] 2.36: RM2000: If a skill causes a state that the target already has, it doesn't try to do the hit condition chance, it always shows the "already" message. If a skill cures a state that the target doesn't have, it's not included in the "condition" list (the skill could miss).
- [x] 2.37: RM2000 + RM2003: If a skill resurrects a character but doesn't have the "affect_hp" checkbox, the effect value will restore the character's %HP (100 or more will restore the character completely). If other stat checkbox are selected, they still gain the same amount of absolute effect value.
- [x] 2.38: RM2000 + RM2003: Skills with physical attributes can only be thrown if the character's weapons (one or two) have all the attributes.
- [x] 2.39: RM2000 + RM2003: Half Cost SP is always rounded to the ceil number.
- [x] 2.40: RM2000: Create animation of enemy self-destructing, similar to Death but their image stretching a little bit.
- [x] 2.41: RM2000: If a battler loses an item or SP in the middle of a turn before their turn is in, and they can't throw that action, their turn becomes NoMove.
- [x] 2.42: RM2000: Implement a Random Agility modifier when deciding the execution order of the battlers (-10%, 10%).
- [x] 2.43: RM2000 + RM2003: A weapon that costs SP only takes it in the first attack. It takes even when the attack misses, and it doesn't take more with double attacks or attacks to all enemies. No change in the attack even if you don't have SP.

3. Damage, absorb and stat decreases:
- [x] 3.1: RM2000: If an attack affects a group, the message display should be:
    · 1st line (+ 2nd line if a skill has one) always stay still.
    · 2nd/3rd line shows the damage results: this line is always replaced when it shows the next enemy damage.
    · 3rd/4th line shows, if the enemy is not dead and the skill causes a condition (poison, etc.), it should show that. If it's various conditions, this line should be replaced by each new condition. This line disappears once it goes to the next enemy damage.
    · 3rd/4th line shows, if the enemy dies, the message of the enemy dying at the same time the enemy vanishes. This line disappears once it goes to the next enemy damage.

- [x] 3.2: RM2000: When replacing a line (like in 3.1), that particular line should flash for 1 or 2 frames instead of changing inmediately. The skill line shouldn't flash.
- [x] 3.3; RM2000: An absorb attack shouldn't make the enemy flash and generate "Damage" sound.
- [x] 3.4: RM2000: An absorb attack should still print all the stats it decreases instead of only the HP.
- [x] 3.5: RM2000: If a skill decreases stats that are not HP, the enemy shouldn't flash and the "Damage" sound shouldn't play.
- [x] 3.6: RM2000: If an enemy doesn't have any more stats to decrease by a skill (and HP is not there), the enemy should "dodge" that attack. If the enemy has at least one stat to decrease, but other who doesn't (and is not HP), that message shouldn't show up at all, instead of appearing as 0.
- [x] 3.7: RM2000: If an enemy dies with an attack that takes away many stats HP included (or puts conditions), the enemy should die right after the HP damage is done, and the other messages are ignored. This also includes absorb attacks.
- [x] 3.8: RM2000: Buffs and bebuffs should be able to stack the more you use them. Also, there is a limit: the modified stats (decrease or increase) only go in the range [-ParameterBase / 2, ParameterBase * 2]. In case the buff/debuff overcomes the limit, it should be clamped and same with the message result. Heal skills (HP and SP) also clamp with the difference healed (so, if Ally 22/30 HP, and uses a potion or heal, it will only show 8).
- [x] 3.9: RM2000: If an absorb skill doesn't take anything, it automatically fails ignoring whether it has some conditions/states to cause.
- [x] 3.10: RM2000: If an attack/skill misses, it shouldn't apply anything and print anything other than the evasion message.
- [x] 3.11: RM2000: Getting all the battle formulas right, including all the modificators.
- [x] 3.12: RM2000 + RM2003: Protection equipment against an element should increase the rate for 1 (at most). This can be combined with Shift attribute.
- [x] 3.13: RM2000 + RM2003: Implement priority for States: The state with the most priority being printed first in ConditionHeal, states with less than 10 priority than the top one being automatically cured, show messages correctly, etc.
- [x] 3.14: RM2000 + RM2003: After a battle is over, heal all the states that despite being "Persist after battle", still have more than 0% chance of recovery (turns and physical recovery don't matter).
- [x] 3.15: RM2000: The Defense resistance should be applied from the beginning of the turn to the end, regardless of when the turn of the battler comes.
- [x] 3.16: RM2000: Attribute modifier is the maximum of the percentage damage of the physical attributes multiplied by the maximum of the percentage damage of the magical attributes.
- [x] 3.17: RM2000 + RM2003: A Weapon's critical chance is added to the critical chance's natural possibility of the actor.
- [x] 3.18: RM2000 + RM2003: If an ally target has a protection with "Prevent Critical hits", then it reduces that to 0.
- [x] 3.19: RM2000: Implement Dual Wield damage by combining their attributes, causing state each weapon by their own probability, combining their critical and hit chance, and showing both animations one after the other.

4. Other stuff:
- [x] 4.1: RM2000 + RM2003: Battle music should start when the TransitionOut from map to battle starts instead of when it ends.
- [x] 4.2: RM2000 + RM2003: There should be white flashes when a battle starts between the battle sound and the TransitionOut. If we look the video in slow motion we can see it's not 1 flash, but two.
- [x] 4.3: RM2000 (not tested in RM2003): If you press "Cancel" when an attack is being made, the "Cancel" sound shouldn't play.
- [x] 4.4: RM2000 (not tested in RM2003): When you use an Item, the "Item" sound should play.
- [x] 4.5: RM2000 + RM2003: The "DECISION" sound when pressing the Attack command should only sound once, not twice.
- [x] 4.6: RM2000 + RM2003: There should be a "DECISION" sound when you press a target (enemy or ally).
- [x] 4.7: RM2000: The Escape sound should sound after the message and when the TransitionOut starts, instead of before the message.
- [x] 4.8: RM2000 + RM2003: When exiting via F12 (Screen Title) in a battle, the TransitionOut should be a quick fadeout, not the same slow defined BattleErased one.
- [x] 4.9: RM2000 + RM2003: The "DECISION" sound when pressing the Defend command should only sound once, not twice.
- [x] 4.10: RM2000: If a technique misses, it doesn't generate EVASION sound unless the "Dodge technique" message is the same as the "physical miss".
- [x] 4.11: RM2000: If you keep CANCEL pressed while in State_Battle, the BattleActionState doesn't advance, it keeps paused.
- [x] 4.12: RM2000 (not tested in RM2003): Maybe it's my impression but when an attack animation shows up to an enemy, shouldn't the enemy flashes inside the animation (not afterwards) be clearer? In the video, sometimes they don't appear.
- [x] 4.13: RM2000: If you keep pressed DECISION while in State_Battle, the waiting time fast-forwards.
- [ ] 4.14: RM2000: Properly calculate the timing between each battle_action_wait for each action.
- [x] 4.15: RM2000 + RM2003: Add Preemptive Attacks (random with normal battles) and all their characteristics.
- [ ] 4.16: RM2003: Other weird stuff (later I edit it, but weird velocity, delay of enemy to die, etc.).

X. Issues unrelated but that happen in the videos:
- [ ] X.1: Midi music should not have those delays in comparison with the RPG_RT.
- [x] X.2: Every sound should correctly play without interruptions, whether in animations or the cursors.

Here are some test videos showing these issues:
    · Sorry for the ocassional spanish, if you have any doubt about some messages please tell me and I'll translate them.

 - Game "The Observer" (RM2000): Random battle. Issues: 1.1, 1.2, 2.3, 2.6, 2.7, 2.9, 2.10, 4.1, 4.2, 4.3, 4.4 (only in the EasyRPG video, but in RM2000 it sounds too), 4.5, 4.6, 4.12.
    · RM2000: http://sendvid.com/sjzlnoug
    · EasyRPG: http://sendvid.com/ue8ityqw

- New RM2000 project: Random battle. Issues: 2.1, 2.2 (these two only happen in the EasyRPG video, but in RM2000 it should work like it's described), 2.3, 2.4 (default skill name: "Skill" / hero's skill name (but unchecked, shouldn't be shown): "Sortilegio"), 2.5, 2.6, 2.7, 2.9 (it doesn't shake, 0 damage) 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7.
    · RM2000: http://sendvid.com/610o0u85
    · EasyRPG: http://sendvid.com/jcls38w2
    · (The bat has 0 MP and 1 intelligence / speed; that's why the skills affect it differently)
    · (Ignore the first seconds, it's a video recording error that I couldn't solve, the rest of the video is fine).

- New RM2003 project: Random battle: Issues: 1.2, 2.3, 4.1, 4.2, 4.5, 4.16.
    · RM2003: http://sendvid.com/ubbz89da
    · EasyRPG: http://sendvid.com/b2bhl6ou

**Comment by fmatthew5876** [comment] 2018-12-06 18:49
We should clear all the checkboxes of this issue and reverify. Only check off things that are in master.

This is how we can ensure no commits were lost to rebasing mistakes.

**Comment by Ghabry** [comment] 2019-02-11 08:58
this is basicly resolved, but I'm also in favor of keeping this open until we looked through our commits to ensure all are fixed.

**Comment by Ghabry** [comment] 2019-02-12 14:33
@fmatthew5876 I searched through the git commits and here are the ones I can't find. They need a manual verification (I'm pretty sure most of them are fixed).

Remaining list:

- [x] 1.1: RM2000: When a Battle Event is executing (whether by "Wait seconds" or an animation loading), the window battle screen should be empty and you shouldn't be able to access commands. 
- ~~1.4: RM2000: If an event page makes all their actions before the message display window is needed to display, the status window should be able to refresh inmediately without skipping a frame (for example, if "Event page: (Turn 0x + 0); DecreaseHP(Player1, 999, Dead)".~~ I flagged this  https://github.com/EasyRPG/Player/pull/1373/commits/c2c3d7e0b8f2d46a9ef289107662575cc32a3c4d and we have another solution for this

2. Message Display:
- [x] 2.8: RM2000: If an enemy causes a condition (poison, sleep, etc.) and fails, the message should be it failed/missed. _I can't even find this in #1373_
- [x] 2.10: RM2000: When a skill or object is used, the skill/object window should stay as it is static and the enemy/ally window over it, instead of hiding the skill/object window. _I hated the solution in https://github.com/EasyRPG/Player/pull/1373/commits/d9f1dec5143120633c4ac98075a4e55951fa3b43 do we have a new one?_
- ~~[x] 2.28: RM2000 + RM2003: If a battler is thrown a state again, the turn count for recovery probability should be the same with no changes, it shouldn't "reset". Probability of state recovery probability should also be only each X turns, not each turn after it surpasses X turn. When the battler is first thrown into a state, if it has 1 turn recovery or more, there should be an extra turn where they do nothing (afterwards it's always a multiple. With 0 turn it happens even in the first turn).~~  This was invalid

3. Damage, absorb and stat decreases:
- [x] 3.4: RM2000: An absorb attack should still print all the stats it decreases instead of only the HP. _Is not in the big PR of albeleon_

4. Other stuff:
- [x] 4.12: RM2000 (not tested in RM2003): Maybe it's my impression but when an attack animation shows up to an enemy, shouldn't the enemy flashes inside the animation (not afterwards) be clearer? In the video, sometimes they don't appear. _not in the big PR_
- [x] 4.15: RM2000 + RM2003: Add Preemptive Attacks (random with normal battles) and all their characteristics.  <- _I think we have this?_
- ~~4.16: RM2003: Other weird stuff (later I edit it, but weird velocity, delay of enemy to die, etc.).~~

**Comment by fmatthew5876** [comment] 2019-02-16 14:36
- [ ] 1.1 - I don't remember this. Needs verification
- [ ] 2.8 - There is no special term for "State inflict failed". I guess he means a miss / skill failure message but its not clear to me exactly the conditions he means. Is he talking about a skill that only inflicts a state and nothing more? A skill that damages and inflicts a state? Need to retest failure messages in all situaitons
- [x] 2.10 - I refactored this. See https://github.com/EasyRPG/Player/blob/master/src/scene_battle_rpg2k.cpp#L163
- [ ] 3.4 - I think this is fixed, but I will retest to be sure. https://github.com/EasyRPG/Player/blob/master/src/game_battlealgorithm.cpp#L613
- [ ] 4.12 - No idea, I need to check this one
- [x] 4.15 - This was fixed in one of my random encounter PRs. https://github.com/EasyRPG/Player/blob/master/src/game_map.cpp#L1130

I'll be stuck with only laptop next week traveling, so I will retest the outstanding items then.

**Comment by fmatthew5876** [comment] 2019-03-01 00:38
I tested all of these, some notes:

* 1.1: This commit doesn't appear in our code. However I can't reproduce a case where a battle event runs and lets you interact with the menus. I tried turn 0, turn 1, and battle events activated by switch
* 2.8: I tested skills with only states and states + damage. We match RPG_RT.
* 4.12: I tested some animations with flash enemy, didn't see any discrepancy.

**Comment by Ghabry** [comment] 2019-03-01 20:45
thanks, I consider this fixed then.

**Closed by Ghabry** 2019-03-01 20:45 UTC
Labels: Battle, Needs feedback
